/* the pattern ID which is defined in UI*/
typedef enum ePattern
{
    OFF_PATT = 0,
    SOLID_DIM_PATT,
    SOLID_ON_PATT,
    SOLID_ON_PATT_GREEN,
    BT_DISCOVERABLE_PATT,
    VOL_LIMIT_REACH_PATT,
    EJECT_BATTERY_PATT,
    CHARGE_BATTERY_PATT,
    SHUTDOWN_BATT_PATT,
    BT_AUTO_LINK_PATT,
    BT_PAIRING_FAIL_PATT,
    IN_COMING_CALL_PATT,
    IN_COMING_CALL_PATT_GREEN,
    ANSWER_END_CALL_PATT,
    ANSWER_END_CALL_PATT_GREEN,
    DELAY_KEEP_OFF_PATT,
    EMERGENCY_MODE_PATT,
    PAT_MAX_NUMBER
}ePattern;

