#ifndef _PATTERN_H
#define _PATTERN_H

#define RGB_LED     0x07


/* the pattern ID which is defined in UI*/
typedef enum
{
    OFF_PATT = 0,
    FADE_IN_0_5s_PATT,
    FADE_OUT_0_5s_PATT,
    SOLID_ON_PATT_WHITE,
    SOLID_ON_PATT_YELLOW,
    SOLID_ON_PATT_GREEN,
    SOLID_ON_PATT_BLUE,
    SOLID_ON_PATT_AMBER,
    SOLID_ON_PATT_PURPLE,
    SOLID_ON_PATT_RED,
    
    BLINKING_PATT_GREEN,
    BLINKING_PATT_BLUE,
    BLINKING_PATT_AMBER,
    BLINKING_PATT_PURPLE,
    
    BLINKING_PATT_RED,
    
    FAST_BLINKING_PATT_GREEN,
    FAST_BLINKING_PATT_BLUE,
    FAST_BLINKING_PATT_AMBER,
    FAST_BLINKING_PATT_PURPLE,
    VERY_FAST_BLINKING_PATT,

    ON_PERIOD_PATT_GREEN,
    ON_PERIOD_PATT_RED,

    SLOW_BLINKING_PATT_AMBER,

    FACTORY_RESET_PATT_1,
    FACTORY_RESET_PATT_2,
    FACTORY_RESET_PATT_3,

    EXIT_IR_LEARNING_MODE_PATT,
    
    PAT_MAX_NUMBER
}ePattern;

typedef enum eIoeAutoPatt
{
    IOE_AUTO_PATT_STBL = 0,
    IOE_AUTO_PATT_MAX,
}eIoeAutoPatt;

#endif
