/*
-------------------------------------------------------------------------------
TYMPHANY LTD





                  Public project Bsp interfaces
                  -------------------------

                  SW Module Document




@file        projBsp.h
@brief       This file implements the public project bsp interfaces which declared
             at projBsp.h
@author      Bob.Xu
@date        2014-07-14
@copyright (c) Tymphany Ltd. All rights reserved.

Change History:
VERSION    : 1    DRAFT      2014-06-12     Bob.Xu
DESCRIPTION: First Draft. Generated by newclass.py
SCO/ERROR  :
-------------------------------------------------------------------------------
*/
#include "stm32f0xx.h"
#include "trace.h"
#include "bsp.h"
#include "projBsp.h"




/* On exception handler, interrupt is disabled, we can not use BSP_BlockingDelayMs()
 * But this delay is not accurary
 */
void BSP_ExpBlockingDelayMs(uint32 ms)
{
#if defined(INTERNAL_HIGH_SPEED_CLOCK)
    uint32 us= 1000 * ms; //8MHz CPU
#elif defined(EXTERNAL_HIGH_SPEED_CLOCK)
    uint32 us= 6000 * ms; //48MHz CPU
#else
    error wrong clock setting
#endif

    while(us--)
    {
        asm("nop");
        asm("nop");
    }
}


void ProjBsp_CyclePrintError(char* errString)
{
    /* To be implemented */
    //ProjBsp_PrintError(); refer to polkAllplayer
    while((*errString)!='\0')
    {
        while(USART_GetFlagStatus(USART1, USART_FLAG_TXE) == RESET);
        USART_SendData(USART1, (*errString));
        errString++;
    }
}

/**************************************************/
/***************  interrupt funcs *********************/
/**************************************************/
/**
  * @brief  This function handles External line 0 interrupt request
  * @param  None
  * @retval None
  */
void EXTI0_1_IRQHandler(void)
{
    if(EXTI_GetITStatus(EXTI_Line0) != RESET)
    {
        EXTI_ClearITPendingBit(EXTI_Line0);
    }
    if(EXTI_GetITStatus(EXTI_Line1) != RESET)
    {
        EXTI_ClearITPendingBit(EXTI_Line1);
    }
}

void EXTI2_3_IRQHandler(void)
{
    //TP_PRINTF("EXTI2_3_IRQHandler\r\n");
    if(EXTI_GetITStatus(EXTI_Line2) != RESET)
    {
        EXTI_ClearITPendingBit(EXTI_Line2);
    }
    if(EXTI_GetITStatus(EXTI_Line3) != RESET)
    {
        EXTI_ClearITPendingBit(EXTI_Line3);
    }
}



void EXTI4_15_IRQHandler(void)
{
    //If set other interrupt between (EXTI_Line5~EXTI_Line15), remember to clear bit

    if (EXTI_GetITStatus(EXTI_Line12))
    {
        EXTI_ClearITPendingBit(EXTI_Line12);

    }

    if (EXTI_GetITStatus(EXTI_Line14))
    {
        EXTI_ClearITPendingBit(EXTI_Line14);

    }

    if (EXTI_GetITStatus(EXTI_Line15))
    {
        EXTI_ClearITPendingBit(EXTI_Line15);

    }
}


void SetEnableWakeupSources()
{

}

void SetDisableWakeupSources()
{

}

/**************************************************/
/************ un-unsed interrupt funcs ****************/
/* User need to remove or fill in the specific function          */
/* if the interrupt is used                                                */
/**************************************************/

void WWDG_IRQHandler(void)
{
    ASSERT(0);
}

void PVD_IRQHandler(void)
{
    ASSERT(0);
}

void TAMPER_IRQHandler(void)
{
    //ASSERT(0);
}

void RTC_IRQHandler(void)
{
    ASSERT(0);
}

void FLASH_IRQHandler(void)
{
    ASSERT(0);
}

void RCC_IRQHandler(void)
{
    ASSERT(0);
}

void EXTI1_IRQHandler(void)
{
    ASSERT(0);
}

void EXTI3_IRQHandler(void)
{
    ASSERT(0);
}

void DMA1_Channel1_IRQHandler(void)
{
    ASSERT(0);
}

void DMA1_Channel2_IRQHandler(void)
{
    ASSERT(0);
}

void DMA1_Channel3_IRQHandler(void)
{
    ASSERT(0);
}

void DMA1_Channel4_IRQHandler(void)
{
    ASSERT(0);
}

void DMA1_Channel5_IRQHandler(void)
{
    ASSERT(0);
}

void DMA1_Channel6_IRQHandler(void)
{
    ASSERT(0);
}

void DMA1_Channel7_IRQHandler(void)
{
    ASSERT(0);
}

void ADC1_2_IRQHandler(void)
{
    ASSERT(0);
}

void CAN1_TX_IRQHandler(void)
{
    ASSERT(0);
}

void CAN1_RX0_IRQHandler(void)
{
    ASSERT(0);
}

void CAN1_RX1_IRQHandler(void)
{
    ASSERT(0);
}

void CAN1_SCE_IRQHandler(void)
{
    ASSERT(0);
}

void TIM1_BRK_IRQHandler(void)
{
    ASSERT(0);
}

void TIM1_UP_IRQHandler(void)
{
    ASSERT(0);
}

void TIM1_TRG_COM_IRQHandler(void)
{
    ASSERT(0);
}

void TIM1_CC_IRQHandler(void)
{
    ASSERT(0);
}

void TIM2_IRQHandler(void)
{
    ASSERT(0);
}

void TIM3_IRQHandler(void)
{
    ASSERT(0);
}

void TIM4_IRQHandler(void)
{
    ASSERT(0);
}

void I2C1_EV_IRQHandler(void)
{
    ASSERT(0);
}

void I2C2_ER_IRQHandler(void)
{
    ASSERT(0);
}

void SPI1_IRQHandler(void)
{
    ASSERT(0);
}

void SPI2_IRQHandler(void)
{
    ASSERT(0);
}

void USART3_IRQHandler(void)
{
    ASSERT(0);
}

void EXTI15_10_IRQHandler(void)
{
    ASSERT(0);
}

void RTCAlarm_IRQHandler(void)
{
    ASSERT(0);
}

void OTG_FS_WKUP_IRQHandler(void)
{
    ASSERT(0);
}

void TIM5_IRQHandler(void)
{
    ASSERT(0);
}


void SPI3_IRQHandler(void)
{
    ASSERT(0);
}


void UART4_IRQHandler(void)
{
    ASSERT(0);
}


void UART5_IRQHandler(void)
{
    ASSERT(0);
}


void TIM6_IRQHandler(void)
{
    ASSERT(0);
}


void TIM7_IRQHandler(void)
{
    ASSERT(0);
}


void DMA2_Channel1_IRQHandler(void)
{
    ASSERT(0);
}


void DMA2_Channel2_IRQHandler(void)
{
    ASSERT(0);
}


void DMA2_Channel3_IRQHandler(void)
{
    ASSERT(0);
}


void DMA2_Channel4_IRQHandler(void)
{
    ASSERT(0);
}


void DMA2_Channel5_IRQHandler(void)
{
    ASSERT(0);
}


void ETH_IRQHandler(void)
{
    ASSERT(0);
}

void ETH_WKUP_IRQHandler(void)
{
    ASSERT(0);
}


void CAN2_TX_IRQHandler(void)
{
    ASSERT(0);
}


void CAN2_RX0_IRQHandler(void)
{
    ASSERT(0);
}


void CAN2_RX1_IRQHandler(void)
{
    ASSERT(0);
}


void CAN2_SCE_IRQHandler(void)
{
    ASSERT(0);
}


void OTG_FS_IRQHandler(void)
{
    ASSERT(0);
}
void ProjBsp_SysClkUpdate()
{
}
