/*
-------------------------------------------------------------------------------
TYMPHANY LTD





                  Public project Bsp interfaces
                  -------------------------

                  SW Module Document




@file        projBsp.h
@brief       This file declares the public project bsp interfaces, user should
             implement these interfaces based on the requiremnets and
             the implementation should be located at projBsp.c
@author      Bob.Xu
@date        2014-06-12
@copyright (c) Tymphany Ltd. All rights reserved.

Change History:
VERSION    : 1    DRAFT      2014-06-12     Bob.Xu
DESCRIPTION: First Draft. Generated by newclass.py
SCO/ERROR  :
-------------------------------------------------------------------------------
*/
#ifndef PROJ_BSP_H
#define PROJ_BSP_H

#include "commonTypes.h"
#include "server.h"
#include "AudioSrv.h"

#define BSP_TICKS_PER_SEC       1000U
#define GET_TICKS_IN_MS(x)      (x * BSP_TICKS_PER_SEC / 1000)
#define INLINE                  inline

enum MainAppPrivSigs
{
   ENERGYSENSE_SIG = MAX_SIG + 1,
   POWER_SWITCH_SIG,
};

#define PCM1862_SLEEP_MODE      (0x09)
#define PCM1862_ACTIVE_MODE     (0x0f)

void SetSender(QActive* sender);

void MuteAdc(bool mute);
uint8 GetAdcMode();
void SwitchEnergySenseMode(bool bIsSigDetection);
void SetEnergySenseMask(eAudioChannel maskChannel);
void projBsp_active_lineIn(void);


#endif /* End of PROJ_BSP_H */