/*
-------------------------------------------------------------------------------
TYMPHANY LTD





                  Tm1629 Driver
                  -------------------------

                  SW Module Document




@file        Tm1629Drv.c
@brief       It's the driver for TM1609 7-seg LED display chip, modified from old driver
@author      Edmond Sung, Johnny Fan, Bob.Xu 
@date        2014-03-10
@copyright (c) Tymphany Ltd. All rights reserved.

Change History:
VERSION    : 1    DRAFT      2014-03-10     Edmond Sung
DESCRIPTION: First Draft. Generated by newclass.py
SCO/ERROR  : 
-------------------------------------------------------------------------------
*/

#include "./DisplayDrv_priv.h"
#include "trace.h"

/* Private functions / variables. Declare and drivers here */
/*******************************************************************************
 *
 * Start-up / shut-down functions
 *
 ******************************************************************************/
void DisplayDrv_Ctor(cDisplayDrv *me)
{
    ASSERT(me);
    DisplayDrv_CleanScrean(me);
}

void DisplayDrv_Xtor(cDisplayDrv *me)
{
    ASSERT(me);
}

/*******************************************************************************
 *
 * Public functions
 *
 ******************************************************************************/
void DisplayDrv_SendString (cDisplayDrv *me, const uchar* pStr)
{
    printf("Display Output: \033[1;32m %s \033[0m\r\n", pStr);
}

 /* brightness off when >= 8 , min..max = 0..7*/
void DisplayDrv_SetBrightness(cDisplayDrv *me, uint8 brtLevel)
{
    ASSERT(me && (brtLevel <= MAX_BRIGHTNESS_LEVEL));
    (void) me;
    (void) brtLevel;
}


/*******************************************************************************
 *
 * private functions
 *
 ******************************************************************************/
void DisplayDrv_CleanScrean(cDisplayDrv *me)
{   
    ASSERT(me);
}
