#ifndef SETTING_ID_H
#define SETTING_ID_H

typedef enum
{
    SETID_START = 0,
    SETID_AUDIO_SOURCE = SETID_START,
    SETID_VOLUME,
    SETID_TREBLE,
    SETID_BASS,
    SETID_BT_STATUS,
    SETID_IS_PWR_SWITH_ON,
    SETID_MUSIC_DET,
    SETID_SYSTEM_SLEEP,
    SETID_IS_AMP_FAULT,
    SETID_HW_VER_STR,
    SETID_JOPLIN_MODEL_ID,
    SETID_HW_STAGE,
    SETID_SW_VER_STR,
    SETID_DSP_VER_STR,
    SETID_BT_VER_STR,
    SETID_REBOOT_CODE,
    SETID_BT_ADDR,
    SETID_EQ_BAND1,
    SETID_EQ_BAND2,
    SETID_EQ_BAND3,
    SETID_EQ_BAND4,
    SETID_EQ_BAND5,
    SETID_STEADY_BRIGHTNESS,
    SETID_DIM_BRIGHTNESS,
    SETID_WORK_MODE,

    SETID_MAX
} eSettingId;


#endif
