#ifndef SETTING_ID_H
#define SETTING_ID_H

typedef enum
{
    SETID_START = 0,
    SETID_AUDIO_SOURCE = SETID_START,
    SETID_VOLUME,
    SETID_TREBLE,
    SETID_BASS,
    SETID_PDL_STATUS,
    SETID_BT_STATUS,
    SETID_IS_AUXIN_PLUG_IN,
    SETID_BATTERY_CAPACITY,
    SETID_MAX
}eSettingId;

#endif
