#ifndef SETTING_ID_H
#define SETTING_ID_H

typedef enum
{
    SETID_START = 0,
    SETID_AUDIO_SOURCE = SETID_START,
    SETID_VOLUME,
    SETID_TREBLE,
    SETID_BASS,
    SETID_BT_STATUS,
    SETID_IS_RCA_ACTIVATED,
    SETID_IS_PWR_SWITH_ON,
    SETID_MUSIC_DET,
    SETID_SYSTEM_SLEEP,
    SETID_HW_VER,
    SETID_MAX
} eSettingId;


#endif
