#ifndef SETTING_ID_H
#define SETTING_ID_H

typedef enum
{
    SETID_START = 0,
    SETID_VOLUME = SETID_START,
    SETID_TREBLE,
    SETID_BASS,
    SETID_DISPLAY_CAPACITY,
    SETID_BT_STATUS,
    SETID_AUDIO_SOURCE,
    SETID_BATTERY_CAPACITY,
    SETID_BATTERY_STATUS,
    SETID_BATTERY_CHARGE_TEMP_LEVEL,
    SETID_BATTERY_DISCHARGE_TEMP_LEVEL,
    SETID_SW_VER,
    SETID_HW_VER,
    SETID_IS_OVER_TEMP,
    SETID_IS_AUXIN_PLUG_IN,
    SETID_IS_PWR_SWITH_ON,
    SETID_MUSIC_DET,
    SETID_BT_BATT_STATUS,
    SETID_IS_DC_PLUG_IN,
    SETID_IS_AMP_FAULT,
    SETID_SHOP_MODE_WORD,
    SETID_BT_VER,
    SETID_DSP_VER,
    SETID_ALLOW_POWERUP,
    SETID_MUSIC_STATUS,
    SETID_CHARGING_STATUS,
    SETID_IS_BATT_VOL_ZERO,
    SETID_IS_BATT_NTC_REMOVED,
    SETID_ALLOW_CHG_PWRUP,
    SETID_STORE_CAPACITY,
    SETID_NTC_TEST_VALUE,
    SETID_MAX
} eSettingId;



#endif
