/*
-------------------------------------------------------------------------------
TYMPHANY LTD





                   infared NEC format Driver
                  -------------------------

                  SW Module Document




@file        NecIrDrv_priv.h
@brief       This file declares the structues and macro related to infared NEC
             format driver.
@author      Bob.Xu 
@date        2014-02-13
@copyright (c) Tymphany Ltd. All rights reserved.

Change History:
VERSION    : 1    DRAFT      2014-07-23     Bob.Xu 
DESCRIPTION: First Draft. Generated by newclass.py
SCO/ERROR  : 
-------------------------------------------------------------------------------
*/

#include "commonTypes.h"
#include "IrRxDrv.h"

#define GPIO_INVALIDD           0
#define RESET_VALUE         0 
#define GPIO_AHPPreiph_Invalid  0
#define EXTI_PortSourceInvalid  0
typedef struct tStmIoInfo
{
    GPIO_TypeDef        *gpioPort;         /* IO port */
    uint32              rccAhbPeriph;     /* port clock ctr bit */
    uint8               exitPortSource; 
}tStmIoInfo;

typedef enum
{
    IR_STATE_IDLE,
    IR_IN_PROGRESS,
    IR_DONE
}eIrState;

//IR decode state
typedef enum
{
    IR_DECODE_ERR = 0,
    IR_DECODE_START,
    IR_DECODE_SUCC,
    IR_DECODE_DONE,
    IR_DECODE_LONG_PRESS
}eIrDecodeState;

typedef struct
{
    uint8               arrIndex ;
    uint32              g_TimerCount;       //to record TIMER1 ticks
    uint32              irArr[38];
    volatile eIrState   irState;
    uint32              command;
    eKeyID              receivedKeyId;
    uint8               releaseCountdown;    
}tNecIrState;

