/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7 at Tue May 16 18:29:09 2017. */

#include "system.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Proto_System_NetworkInfo_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, Proto_System_NetworkInfo, networkInterface, networkInterface, &Proto_System_NetworkInfo_NetworkInterface_fields),
    PB_LAST_FIELD
};

const pb_field_t Proto_System_NetworkInfo_NetworkInterface_fields[4] = {
    PB_FIELD(  1, ENUM   , OPTIONAL, STATIC  , FIRST, Proto_System_NetworkInfo_NetworkInterface, type, type, 0),
    PB_FIELD(  2, ENUM   , OPTIONAL, STATIC  , OTHER, Proto_System_NetworkInfo_NetworkInterface, state, type, 0),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, Proto_System_NetworkInfo_NetworkInterface, wifi, state, &Proto_System_NetworkInfo_NetworkInterface_WiFi_fields),
    PB_LAST_FIELD
};

const pb_field_t Proto_System_NetworkInfo_NetworkInterface_WiFi_fields[3] = {
    PB_FIELD(  1, BOOL    , OPTIONAL, STATIC  , FIRST, Proto_System_NetworkInfo_NetworkInterface_WiFi, Configured, Configured, 0),
    PB_FIELD(  2, ENUM   , OPTIONAL, STATIC  , OTHER, Proto_System_NetworkInfo_NetworkInterface_WiFi, quality, Configured, 0),
    PB_LAST_FIELD
};

const pb_field_t Proto_System_PowerStatus_fields[6] = {
    PB_FIELD(  1, ENUM   , OPTIONAL, STATIC  , FIRST, Proto_System_PowerStatus, acLineStatus, acLineStatus, 0),
    PB_FIELD(  2, ENUM   , OPTIONAL, STATIC  , OTHER, Proto_System_PowerStatus, batteryStatus, acLineStatus, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, Proto_System_PowerStatus, batteryLevel, batteryStatus, 0),
    PB_FIELD(  4, ENUM   , OPTIONAL, STATIC  , OTHER, Proto_System_PowerStatus, healthStatus, batteryLevel, 0),
    PB_FIELD(  5, BOOL    , OPTIONAL, STATIC  , OTHER, Proto_System_PowerStatus, charging, healthStatus, 0),
    PB_LAST_FIELD
};

const pb_field_t Proto_System_Log_fields[2] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, FIRST, Proto_System_Log, msg, msg, 0),
    PB_LAST_FIELD
};

const pb_field_t Proto_System_PowerRequest_fields[3] = {
    PB_FIELD(  1, ENUM   , OPTIONAL, STATIC  , FIRST, Proto_System_PowerRequest, type, type, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, Proto_System_PowerRequest, delay_ms, type, 0),
    PB_LAST_FIELD
};

const pb_field_t Proto_System_Voltage_fields[3] = {
    PB_FIELD(  1, ENUM   , OPTIONAL, STATIC  , FIRST, Proto_System_Voltage, type, type, 0),
    PB_FIELD(  2, DOUBLE  , OPTIONAL, STATIC  , OTHER, Proto_System_Voltage, value, type, 0),
    PB_LAST_FIELD
};

const pb_field_t Proto_System_PowerSupplyVoltage_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, Proto_System_PowerSupplyVoltage, voltage, voltage, &Proto_System_Voltage_fields),
    PB_LAST_FIELD
};

const pb_field_t Proto_System_RespGetBoardVersion_fields[5] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, FIRST, Proto_System_RespGetBoardVersion, bomVariantString, bomVariantString, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, CALLBACK, OTHER, Proto_System_RespGetBoardVersion, bomVariantLetter, bomVariantString, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, Proto_System_RespGetBoardVersion, pcbaVariant, bomVariantLetter, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, CALLBACK, OTHER, Proto_System_RespGetBoardVersion, pcbaVariantString, pcbaVariant, 0),
    PB_LAST_FIELD
};

const pb_field_t Proto_System_AudioCue_fields[2] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, FIRST, Proto_System_AudioCue, name, name, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Proto_System_NetworkInfo, networkInterface[0]) < 65536 && pb_membersize(Proto_System_NetworkInfo_NetworkInterface, wifi) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Proto_System_NetworkInfo_Proto_System_NetworkInfo_NetworkInterface_Proto_System_NetworkInfo_NetworkInterface_WiFi_Proto_System_PowerStatus_Proto_System_Log_Proto_System_PowerRequest_Proto_System_Voltage_Proto_System_PowerSupplyVoltage_Proto_System_RespGetBoardVersion_Proto_System_AudioCue)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Proto_System_NetworkInfo, networkInterface[0]) < 256 && pb_membersize(Proto_System_NetworkInfo_NetworkInterface, wifi) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Proto_System_NetworkInfo_Proto_System_NetworkInfo_NetworkInterface_Proto_System_NetworkInfo_NetworkInterface_WiFi_Proto_System_PowerStatus_Proto_System_Log_Proto_System_PowerRequest_Proto_System_Voltage_Proto_System_PowerSupplyVoltage_Proto_System_RespGetBoardVersion_Proto_System_AudioCue)
#endif


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
