/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Thu Mar 22 17:57:34 2018. */

#include "ble_eq_tuning.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Proto_BleEqTuning_Data_fields[2] = {
    PB_FIELD(  1, BYTES   , REQUIRED, STATIC  , FIRST, Proto_BleEqTuning_Data, eq, eq, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
