/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Mon Dec 18 16:01:24 2017. */

#include "bt-mcu.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Proto_BtMcu_Req_fields[4] = {
    PB_FIELD(  1, ENUM   , OPTIONAL, STATIC  , FIRST, Proto_BtMcu_Req, type, type, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, Proto_BtMcu_Req, id, type, 0),
    PB_ONEOF_FIELD(data,  10, MESSAGE , ONEOF, STATIC  , OTHER, Proto_BtMcu_Req, dspAbsoluteVolume, id, &Proto_TymDsp_AbsoluteVolume_fields),
    PB_LAST_FIELD
};

const pb_field_t Proto_BtMcu_Resp_fields[5] = {
    PB_FIELD(  1, ENUM   , OPTIONAL, STATIC  , FIRST, Proto_BtMcu_Resp, type, type, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, Proto_BtMcu_Resp, id, type, 0),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, Proto_BtMcu_Resp, genericResponse, id, &Proto_Tym_GenericResponse_fields),
    PB_ONEOF_FIELD(data,  10, MESSAGE , ONEOF, STATIC  , OTHER, Proto_BtMcu_Resp, volume, genericResponse, &Proto_TymDsp_AbsoluteVolume_fields),
    PB_LAST_FIELD
};

const pb_field_t Proto_BtMcu_Event_fields[8] = {
    PB_FIELD(  1, ENUM   , OPTIONAL, STATIC  , FIRST, Proto_BtMcu_Event, type, type, 0),
    PB_ONEOF_FIELD(OneOf,   9, UINT32  , ONEOF, STATIC  , OTHER, Proto_BtMcu_Event, data, type, 0),
    PB_ONEOF_FIELD(OneOf,  10, MESSAGE , ONEOF, STATIC  , UNION, Proto_BtMcu_Event, volume, type, &Proto_TymDsp_AbsoluteVolume_fields),
    PB_ONEOF_FIELD(OneOf,  11, MESSAGE , ONEOF, STATIC  , UNION, Proto_BtMcu_Event, mute, type, &Proto_TymDsp_Mute_fields),
    PB_ONEOF_FIELD(OneOf,  12, ENUM    , ONEOF, STATIC  , UNION, Proto_BtMcu_Event, connState, type, 0),
    PB_ONEOF_FIELD(OneOf,  14, ENUM    , ONEOF, STATIC  , UNION, Proto_BtMcu_Event, playState, type, 0),
    PB_ONEOF_FIELD(OneOf,  15, ENUM    , ONEOF, STATIC  , UNION, Proto_BtMcu_Event, bleState, type, 0),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Proto_BtMcu_Req, data.dspAbsoluteVolume) < 65536 && pb_membersize(Proto_BtMcu_Resp, data.volume) < 65536 && pb_membersize(Proto_BtMcu_Resp, genericResponse) < 65536 && pb_membersize(Proto_BtMcu_Event, OneOf.volume) < 65536 && pb_membersize(Proto_BtMcu_Event, OneOf.mute) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Proto_BtMcu_Req_Proto_BtMcu_Resp_Proto_BtMcu_Event)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Proto_BtMcu_Req, data.dspAbsoluteVolume) < 256 && pb_membersize(Proto_BtMcu_Resp, data.volume) < 256 && pb_membersize(Proto_BtMcu_Resp, genericResponse) < 256 && pb_membersize(Proto_BtMcu_Event, OneOf.volume) < 256 && pb_membersize(Proto_BtMcu_Event, OneOf.mute) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Proto_BtMcu_Req_Proto_BtMcu_Resp_Proto_BtMcu_Event)
#endif


/* @@protoc_insertion_point(eof) */
