/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Mon Dec 18 16:01:24 2017. */

#include "mcu-bt.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Proto_McuBt_Event_fields[2] = {
    PB_FIELD(  1, ENUM   , OPTIONAL, STATIC  , FIRST, Proto_McuBt_Event, type, type, 0),
    PB_LAST_FIELD
};

const pb_field_t Proto_McuBt_Req_fields[5] = {
    PB_FIELD(  1, ENUM   , OPTIONAL, STATIC  , FIRST, Proto_McuBt_Req, type, type, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, Proto_McuBt_Req, id, type, 0),
    PB_ONEOF_FIELD(data,  10, MESSAGE , ONEOF, STATIC  , OTHER, Proto_McuBt_Req, absoluteVolume, id, &Proto_TymDsp_AbsoluteVolume_fields),
    PB_ONEOF_FIELD(data,  11, MESSAGE , ONEOF, STATIC  , UNION, Proto_McuBt_Req, relativeVolumeChange, id, &Proto_TymDsp_RelativeVolumeChange_fields),
    PB_LAST_FIELD
};

const pb_field_t Proto_McuBt_Resp_fields[6] = {
    PB_FIELD(  1, ENUM   , OPTIONAL, STATIC  , FIRST, Proto_McuBt_Resp, type, type, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, Proto_McuBt_Resp, id, type, 0),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, Proto_McuBt_Resp, genericResponse, id, &Proto_Tym_GenericResponse_fields),
    PB_ONEOF_FIELD(data,  10, MESSAGE , ONEOF, STATIC  , OTHER, Proto_McuBt_Resp, volume, genericResponse, &Proto_TymDsp_AbsoluteVolume_fields),
    PB_ONEOF_FIELD(data,  11, MESSAGE , ONEOF, STATIC  , UNION, Proto_McuBt_Resp, relativeVolumeChange, genericResponse, &Proto_TymDsp_RelativeVolumeChange_fields),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Proto_McuBt_Req, data.absoluteVolume) < 65536 && pb_membersize(Proto_McuBt_Req, data.relativeVolumeChange) < 65536 && pb_membersize(Proto_McuBt_Resp, data.volume) < 65536 && pb_membersize(Proto_McuBt_Resp, data.relativeVolumeChange) < 65536 && pb_membersize(Proto_McuBt_Resp, genericResponse) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Proto_McuBt_Event_Proto_McuBt_Req_Proto_McuBt_Resp)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Proto_McuBt_Req, data.absoluteVolume) < 256 && pb_membersize(Proto_McuBt_Req, data.relativeVolumeChange) < 256 && pb_membersize(Proto_McuBt_Resp, data.volume) < 256 && pb_membersize(Proto_McuBt_Resp, data.relativeVolumeChange) < 256 && pb_membersize(Proto_McuBt_Resp, genericResponse) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Proto_McuBt_Event_Proto_McuBt_Req_Proto_McuBt_Resp)
#endif


/* @@protoc_insertion_point(eof) */
