/* the pattern ID which is defined in UI*/
typedef enum ePattern
{
    OFF_PATT = 0,
    STANDBY_PAT,
    SOLID_PAT,
    SAM_BOOTING_UP_PAT,
    POWER_UP_DOWN_PAT,
    NET_CONNECTING_PAT,
    NET_FAIL_PAT,
    RST_IN_PROG_PAT,
    DFU_PROG_PAT,
    VALID_BUT_PRESS_PAT,
    VOL_MAX_OFF_PAT,                
    VOL_MAX_PAT,
    VOL_MIN_OFF_PAT,
    VOL_MIN_PAT,               
    HW_ERR_PAT,
    DIRECT_INIT_PAT,
    DISPLAY_SWV_START_PAT,
    DISPLAY_SWV_END_PAT,
    APP_MAJOR_VER_PAT,
    APP_MINOR_VER_PAT1,
    APP_MINOR_VER_PAT2,
    BOOT_LOADER_MAJOR_VER_PAT,
    BOOT_LOADER_MINOR_VER_PAT1,
    BOOT_LOADER_MINOR_VER_PAT2,
    BT_PAIRING_ENABLE_PAT,
    BT_RECONNECTINT_PAT,
    PAT_MAX_NUMBER
}ePattern;

