/*****************************************************************************
* Model: tym_platform.qm
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/**
 *  @file      HdmiSrv.h
 *  @brief     This file contains the HDMI driver implementation.
 *  @author    Neo
 *  @date      24-Aug-2017
 */
#ifndef HDMISRV_PRIV_H
#define HDMISRV_PRIV_H

#include "server.h"
#include "HdmiSrv.h"

QState HdmiSrv_Initial(cHdmiSrv * const me, QEvt const * const e);
QState HdmiSrv_PreActive(cHdmiSrv * const me, QEvt const * const e);
QState HdmiSrv_Active(cHdmiSrv * const me, QEvt const * const e);
QState HdmiSrv_DeActive(cHdmiSrv * const me, QEvt const * const e);

#endif /* HDMISRV_PRIV_H */

