/*
-------------------------------------------------------------------------------
TYMPHANY LTD





                  Public project Bsp interfaces
                  -------------------------

                  SW Module Document




@file        projBsp.h
@brief       This file declares the public project bsp interfaces, user should
             implement these interfaces based on the requiremnets and
             the implementation should be located at projBsp.c
@author      Bob.Xu
@date        2014-06-12
@copyright (c) Tymphany Ltd. All rights reserved.

Change History:
VERSION    : 1    DRAFT      2014-06-12     Bob.Xu
DESCRIPTION: First Draft. Generated by newclass.py
SCO/ERROR  :
-------------------------------------------------------------------------------
*/
#ifndef PROJ_BSP_H
#define PROJ_BSP_H

#include "commonTypes.h"
#include "server.h"
#include "AudioSrv.h"

#define INLINE                  inline

enum MainAppPrivSigs
{
   ENERGYSENSE_SIG = 210,
   POWER_SWITCH_INT_SIG,
   DC_IN_INT_SIG
};

void ProjBsp_SysClkUpdate();
void SetDisableWakeupSources(void);
void SetEnableWakeupSources(void);
void SetSender(QActive* sender);

#endif /* End of PROJ_BSP_H */
