/*
-------------------------------------------------------------------------------
TYMPHANY LTD





                  Tm1629 Driver
                  -------------------------

                  SW Module Document




@file        Tm1629Drv.c
@brief       It's the driver for TM1609 7-seg LED display chip, modified from old driver
@author      Edmond Sung, Bob.Xu 
@date        2014-03-10
@copyright (c) Tymphany Ltd. All rights reserved.

Change History:
VERSION    : 1    DRAFT      2014-03-10     Edmond Sung
DESCRIPTION: First Draft. Generated by newclass.py
SCO/ERROR  : 
-------------------------------------------------------------------------------
*/

#ifndef TM1629_DRIVER_H
#define TM1629_DRIVER_H

#ifdef __cplusplus
extern "C" {
#endif

#include "cplus.h"
#include "deviceTypes.h"
#include "GpioDrv.h"

CLASS(cDisplayDrv)
    /* private data */
    cGpioDrv* gpioDrv;
METHODS

/* public functions */
void DisplayDrv_Ctor(cDisplayDrv *me);
void DisplayDrv_Xtor(cDisplayDrv *me);
void DisplayDrv_SendChar(cDisplayDrv *me, uint8 charPos, uint8 ch);
void DisplayDrv_SendChar_WithDot (cDisplayDrv *me, uint8 charPos, uint8 ch) ;
void DisplayDrv_SendString (cDisplayDrv *me, const uchar* pStr);
void DisplayDrv_SetBrightness(cDisplayDrv *me, uint8 brtLevel);
void DisplayDrv_CleanScrean(cDisplayDrv *me);
void DisplayDrv_SetDebugType(cDisplayDrv *me, int8 chPosition, int8 segId);
END_CLASS

#ifdef __cplusplus
}
#endif

#endif /* TM1629_DRIVER_H */

