#ifndef SETTING_ID_H
#define SETTING_ID_H

typedef enum
{
    SETID_START = 0,
    SETID_DSP_INIT_DATA  = SETID_START,
    SETID_DSP_TUNABLE_PART,
    SETID_VOLUME,
    SETID_MUSIC_DET,
    SETID_MENU_DATA,
    SETID_PRESET_1,
    SETID_PRESET_2,
    SETID_PRESET_3,
    SETID_PRESET_1_NAME,
    SETID_PRESET_2_NAME,
    SETID_PRESET_3_NAME,
    SETID_MAX
}eSettingId;


#endif
