#ifndef SETTING_ID_H
#define SETTING_ID_H

typedef enum
{
    SETID_START = 0,
    SETID_VOLUME = SETID_START,
    SETID_CHANNEL,
    SETID_IS_AUXIN_PLUG_IN,
    SETID_MAX_VOLUME,
    SETID_MUSIC_DET,
    SETID_IR_LEARN_CODE,
    SETID_SOURCE_OBJECT,
    SETID_CURRENT_SOURCE,
    SETID_MAGIC_NUMBER,
    SETID_MAX
}eSettingId;


#endif
