/*
-------------------------------------------------------------------------------
TYMPHANY LTD





                  Public project Bsp interfaces
                  -------------------------

                  SW Module Document




@file        projBsp.h
@brief       This file implements the public project bsp interfaces which declared
             at projBsp.h
@author      Bob.Xu
@date        2014-07-14
@copyright (c) Tymphany Ltd. All rights reserved.

Change History:
VERSION    : 1    DRAFT      2014-06-12     Bob.Xu
DESCRIPTION: First Draft. Generated by newclass.py
SCO/ERROR  :
-------------------------------------------------------------------------------
*/
#include "stm32f0xx.h"

#include "bsp.h"
#include "projBsp.h"
#include "KeySrv.h"
#include "I2CDrv.h"
#include "AudioAdcDrv.h"
#include "AudioSrv.h"
#include "setting_id.h"

static QActive* pSender = NULL;


void SetSender(QActive* sender)
{
    pSender = sender;
}

void ProjBsp_SysClkUpdate()
{
}
