/******************************************************************************

Copyright (c) 2015, Tymphany HK Ltd. All rights reserved.

Confidential information of Tymphany HK Ltd.

The Software is provided "AS IS" and "WITH ALL FAULTS," without warranty of any
kind, including without limitation the warranties of merchantability, fitness
for a particular purpose and non-infringement. Tymphany HK LTD. makes no
warranty that the Software is free of defects or is suitable for any particular
purpose.

******************************************************************************/

#ifndef _PATTERN_H
#define _PATTERN_H

#include "attachedDevices.h"


/* the pattern ID which is defined in UI*/
typedef enum
{
    OFF_PATT = 0,
    FG_OFF_PATT,

    //BG solid
    BG_WHITE_PAT,
    BG_RED_PAT,
    BG_ORANGE_PAT,
    BG_BLUE_PAT,
    BG_GREEN_PAT,
    BG_YELLOW_PAT,
    
    //FG solid
    FG_WHITE_LONG_PAT,
    FG_RED_LONG_PAT,
    FG_RED_LONG_2S_PAT,  //for power down
    FG_BLUE_LONG_2S_PAT,  //BL Paring Success
    FG_RED_LONG_4S_PAT,
    FG_WHITE_LONG_10S_PAT, //for playback start/stop
    FG_RED_LONG_10S_PAT, //for playback start/stop
    
    //BG solid dim
    BG_WHITE_DIM_PAT,
    BG_RED_DIM_PAT,
    BG_ORANGE_DIM_PAT,
    BG_BLUE_DIM_PAT,
    
    //BG flash
    BG_WHITE_FLASH_PAT,
    BG_RED_FLASH_PAT,
    BG_ORANGE_FLASH_PAT,
    BG_BLUE_FLASH_PAT,
    
    //BG quick flash
    BG_WHITE_QUICK_FLASH_PAT,
    BG_RED_QUICK_FLASH_PAT,
    BG_ORANGE_QUICK_FLASH_PAT,

    //FG quick flash
    FG_WHITE_QUICK_FLASH_ONCE_PAT,
    FG_RED_QUICK_FLASH_ONCE_PAT,
    FG_WHITE_QUICK_FLASH_TWICE_PAT,
    FG_RED_QUICK_FLASH_TWICE_PAT,
    FG_WHITE_QUICK_FLASH_THRICE_PAT,
    FG_RED_QUICK_FLASH_2S_PAT,
    FG_RED_QUICK_FLASH_10S_PAT,
    
    //FG slow flash
    FG_WHT_SLOW_FLASH_4S_PAT,
    FG_RED_SLOW_FLASH_4S_PAT,
    
    //BG slow flash
    BG_ORANGE_SLOW_FLASH_PAT,
    
    //BG pulse
    BG_WHITE_PULSE_PAT,
    BG_RED_PULSE_PAT,
    BG_ORANGE_PULSE_PAT,
    BG_BLUE_PULSE_PAT,
            
    //BG double color
    BG_COLORFUL_PART1_PAT,
    BG_COLORFUL_PART2_PAT,
    BG_COLORFUL_PART3_PAT,
    BG_COLORFUL_PART4_PAT,
    BG_COLORFUL_PART5_PAT,
    BG_COLORFUL_PART6_PAT,
    BG_COLORFUL_PART7_PAT,
    BG_COLORFUL_PART8_PAT,

    FG_PROD_TOUCH_NOISE_PAT,
            
    //FG trans to OFF
    FG_WHITE_TRANS_TO_OFF_PART1_PAT,
    FG_WHITE_TRANS_TO_OFF_PART2_PAT,
    FG_WHITE_TRANS_TO_OFF_PART3_PAT,
    FG_RED_TRANS_TO_OFF_PART1_PAT,
    FG_RED_TRANS_TO_OFF_PART2_PAT,
    FG_RED_TRANS_TO_OFF_PART3_PAT,
    FG_PREV_TRANS_TO_OFF_PART1_PAT,
    FG_PREV_TRANS_TO_OFF_PART2_PAT,
    FG_PREV_TRANS_TO_OFF_PART3_PAT,
    
    PAT_MAX_NUMBER
}ePattern;

typedef enum eIoeAutoPatt
{
    IOE_AUTO_PATT_STBL = 0,
    IOE_AUTO_PATT_ERROR,
    IOE_AUTO_PATT_MAX,
}eIoeAutoPatt;

typedef struct _tLed_Ind
{
    ledMask     leds;
    ePattern    patternId;
} tLedInd;

/* Please add LED indicaitons according to the UI design of your project. */
typedef enum _eLedIndID
{
    LED_IND_ID_POWERING_UP = 0,
    LED_IND_ID_POWERING_DOWN_CONN_WHITE,
    LED_IND_ID_POWERING_DOWN_CONN_RED,
    LED_IND_ID_POWERING_DOWN_CONN_PRIV,
    LED_IND_ID_POWERING_DOWN_PROD_WHITE,
    LED_IND_ID_POWERING_DOWN_PROD_RED,
    LED_IND_ID_POWERING_DOWN_PROD_PREV,
    LED_IND_ID_POWERING_DOWN_ERROR,
    
    LED_IND_ID_NETWORK_STANDBY_PROD,
    LED_IND_ID_NETWORK_STANDBY_CONN,
    LED_IND_ID_ENTER_STORAGE,
    LED_IND_ID_WIFI_UNCONFIGURED,
    LED_IND_ID_WIFI_UNCONFIGURED_IDLE,
    LED_IND_ID_RST_IN_PROG,
    
    LED_IND_ID_WIFI_MODE_QUALITY_EXELENT,
    LED_IND_ID_WIFI_MODE_QUALITY_EXELENT_IDLE,
    LED_IND_ID_WIFI_MODE_QUALITY_GOOD,
    LED_IND_ID_WIFI_MODE_QUALITY_GOOD_IDLE,
    LED_IND_ID_WIFI_MODE_QUALITY_POOR,
    LED_IND_ID_WIFI_MODE_QUALITY_POOR_IDLE,
    LED_IND_ID_WIFI_CONNECTING,
    LED_IND_ID_WIFI_CONNECT_FAIL,
    LED_IND_ID_ETHERNET_MODE,
    LED_IND_ID_ETHERNET_MODE_IDLE,
    LED_IND_ID_SOFTAP_MODE,
    LED_IND_ID_ERROR,
    
    LED_IND_ID_TOUCH_KEY_WHT_ON_LONG,
    LED_IND_ID_TOUCH_KEY_RED_ON_LONG,
    LED_IND_ID_TOUCH_KEY_FLASH_WHT_ONCE,
    
    LED_IND_ID_TOUCH_KEY_FLASH_RED_ONCE,    
    LED_IND_ID_TOUCH_KEY_FLASH_WHT_TWICE,
    LED_IND_ID_TOUCH_KEY_FLASH_RED_TWICE,
    LED_IND_ID_TOUCH_KEY_FLASH_WHT_THRICE,
    LED_IND_ID_TOUCH_KEY_FLASH_RED_THRICE,
    LED_IND_ID_KEY_SP,
    LED_IND_ID_KEY_LP,
    LED_IND_ID_KEY_VLP,
    LED_IND_ID_KEY_DP,
    LED_IND_ID_KEY_SWIPE,
    
    LED_IND_ID_FACTORY_RESET_TRIGGER,
    LED_IND_ID_PLAYING,
    LED_IND_ID_PLAYING_DIM,
    LED_IND_ID_BT_PAIRING_ENABLED,
    LED_IND_ID_BT_PAIRING_FAIL,
    LED_IND_ID_BT_PAIRING_SUCCESS,
        
    LED_IND_ID_BATT_LOW_NO_DC,
    LED_IND_ID_BATT_LOW_HAVE_DC,
    
    LED_IND_ID_FIRST_BOOT,
    LED_IND_ID_SW_UPDATING,
    LED_IND_ID_EXT_SOURCE, //fs1:SPDIF, fs2:LINE-IN
    LED_IND_ID_DSP_ONLINE_TUNING,
    LED_IND_ID_FAST_BOOT,
    LED_IND_ID_GOLDEN_SAMPLE,
    LED_IND_ID_TOUCH_NOISE,
    
    LED_IND_ID_CHANNEL_NORMAL,
    LED_IND_ID_CHANNEL_LEFT,
    LED_IND_ID_CHANNEL_RIGHT,
    
    LED_IND_ID_CONN_FG_OFF,
    LED_IND_ID_PROD_FG_OFF,
    LED_IND_ID_ALL_FG_OFF,

    LED_IND_ID_CONN_OFF,
    LED_IND_ID_PROD_OFF,    
    LED_IND_ID_ALL_BG_OFF,
    
    LED_IND_ID_LED1_RED_BG_ON,
    LED_IND_ID_LED2_ORG_BG_ON,
    LED_IND_ID_LED3_BLUE_BG_ON,
    LED_IND_ID_LED4_WHT_BG_ON,
    LED_IND_ID_LED5_WHT_BG_ON,
    LED_IND_ID_LED6_WHT_BG_ON,
    LED_IND_ID_LED7_ORG_BG_ON,
    LED_IND_ID_LED8_WHT_BG_ON,
    LED_IND_ID_LED9_ORG_BG_ON,
    LED_IND_ID_LED10_YEL_BG_ON,
    LED_IND_ID_LED11_ORG_BG_ON,
    LED_IND_ID_LED12_WHT_BG_ON,
    LED_IND_ID_LED13_ORG_BG_ON,
    LED_IND_ID_LED14_WHT_BG_ON,
    LED_IND_ID_LED15_WHT_BG_ON,
    LED_IND_ID_LED16_GRE_BG_ON,
    LED_IND_ID_LED17_BLUE_BG_ON,
    LED_IND_ID_LED18_RED_BG_ON,
    LED_IND_ID_LED19_ORG_BG_ON,
    LED_IND_ID_LED20_WHT_BG_ON,
    LED_IND_ID_MAX
}eLedIndID;

/* Please config below LED mask according to the HW design of your project. */
typedef enum _eLedMask
{
    LED_MASK_MIN           = 0,
    LED_MASK_LED1_RED      = 1 << (LED1_CONN_RED),
    LED_MASK_LED2_ORG      = 1 << (LED2_CONN_ORG), 
    LED_MASK_LED3_BLUE     = 1 << (LED3_CONN_BLUE),
    LED_MASK_LED4_WHT      = 1 << (LED4_CONN_WHT), 
    LED_MASK_LED5_WHT      = 1 << (LED5_PROD_WHT),
    LED_MASK_LED6_WHT      = 1 << (LED6_PROD_WHT), 
    LED_MASK_LED7_ORG      = 1 << (LED7_PROD_ORG), 
    LED_MASK_LED8_WHT      = 1 << (LED8_PROD_WHT), 
    LED_MASK_LED9_ORG      = 1 << (LED9_PROD_ORG), 
    LED_MASK_LED10_YEL     = 1 << (LED10_GOOGLE_YEL),//Google LED
    LED_MASK_LED11_ORG     = 1 << (LED11_PROD_ORG),
    LED_MASK_LED12_WHT     = 1 << (LED12_PROD_WHT),
    LED_MASK_LED13_ORG     = 1 << (LED13_PROD_ORG),
    LED_MASK_LED14_WHT     = 1 << (LED14_PROD_WHT),
    LED_MASK_LED15_WHT     = 1 << (LED15_ALWAYS_ON_WHT),//15 pin used as a output port
    LED_MASK_LED16_GRE     = 1 << (LED16_GOOGLE_GRE),//Google LED
    LED_MASK_LED17_BLUE    = 1 << (LED17_GOOGLE_BLUE),//Google LED
    LED_MASK_LED18_RED     = 1 << (LED18_GOOGLE_RED),//Google LED
    LED_MASK_LED19_ORG     = 1 << (LED19_PROD_ORG),
    LED_MASK_LED20_WHT     = 1 << (LED20_PROD_WHT),

    LED_MASK_CONN_LEDS    = 0x0000f,
    LED_MASK_GOOGLE_LEDS  = 0x38200,
    LED_MASK_PROD_LEDS    = 0xC3DF0,
    LED_MASK_PROD_LED_RED = LED_MASK_LED18_RED,
    LED_MASK_CONN_LED_RED = LED_MASK_LED1_RED,
    LED_MASK_ALL_LEDS     = 0xfbfff,//0x0000f,//0xfbfff,//15 pin used as a output port
    LED_MASK_MAX
}eLedMask;

#endif
