/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7 at Mon Apr 17 15:09:20 2017. */

#ifndef PB_PROTO_POWERLINK_POWER_LINK_PB_H_INCLUDED
#define PB_PROTO_POWERLINK_POWER_LINK_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _Proto_PowerLink_AllSensesStatus {
    char dummy_field;
/* @@protoc_insertion_point(struct:Proto_PowerLink_AllSensesStatus) */
} Proto_PowerLink_AllSensesStatus;

typedef struct _Proto_PowerLink_AllSensesStatus_PortState {
    char dummy_field;
/* @@protoc_insertion_point(struct:Proto_PowerLink_AllSensesStatus_PortState) */
} Proto_PowerLink_AllSensesStatus_PortState;

typedef struct _Proto_PowerLink_Data {
    char dummy_field;
/* @@protoc_insertion_point(struct:Proto_PowerLink_Data) */
} Proto_PowerLink_Data;

typedef struct _Proto_PowerLink_SenseEvent {
    char dummy_field;
/* @@protoc_insertion_point(struct:Proto_PowerLink_SenseEvent) */
} Proto_PowerLink_SenseEvent;

typedef struct _Proto_PowerLink_SetMute {
    char dummy_field;
/* @@protoc_insertion_point(struct:Proto_PowerLink_SetMute) */
} Proto_PowerLink_SetMute;

typedef struct _Proto_PowerLink_SetON {
    char dummy_field;
/* @@protoc_insertion_point(struct:Proto_PowerLink_SetON) */
} Proto_PowerLink_SetON;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Proto_PowerLink_SenseEvent_init_default  {0}
#define Proto_PowerLink_AllSensesStatus_init_default {0}
#define Proto_PowerLink_AllSensesStatus_PortState_init_default {0}
#define Proto_PowerLink_SetON_init_default       {0}
#define Proto_PowerLink_SetMute_init_default     {0}
#define Proto_PowerLink_Data_init_default        {0}
#define Proto_PowerLink_SenseEvent_init_zero     {0}
#define Proto_PowerLink_AllSensesStatus_init_zero {0}
#define Proto_PowerLink_AllSensesStatus_PortState_init_zero {0}
#define Proto_PowerLink_SetON_init_zero          {0}
#define Proto_PowerLink_SetMute_init_zero        {0}
#define Proto_PowerLink_Data_init_zero           {0}

/* Field tags (for use in manual encoding/decoding) */

/* Struct field encoding specification for nanopb */
extern const pb_field_t Proto_PowerLink_SenseEvent_fields[1];
extern const pb_field_t Proto_PowerLink_AllSensesStatus_fields[1];
extern const pb_field_t Proto_PowerLink_AllSensesStatus_PortState_fields[1];
extern const pb_field_t Proto_PowerLink_SetON_fields[1];
extern const pb_field_t Proto_PowerLink_SetMute_fields[1];
extern const pb_field_t Proto_PowerLink_Data_fields[1];

/* Maximum encoded size of messages (where known) */
#define Proto_PowerLink_SenseEvent_size          0
#define Proto_PowerLink_AllSensesStatus_size     0
#define Proto_PowerLink_AllSensesStatus_PortState_size 0
#define Proto_PowerLink_SetON_size               0
#define Proto_PowerLink_SetMute_size             0
#define Proto_PowerLink_Data_size                0

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define POWER_LINK_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
