/*
-------------------------------------------------------------------------------
TYMPHANY LTD





                  Eeprom Driver
                  -------------------------

                  SW Module Document




@file        EepromDrv.c
@brief       It's the driver for read/write external EEPROM
@author      Johnny Fan 
@date        2014-03-31
@copyright (c) Tymphany Ltd. All rights reserved.

Change History:
VERSION    : 1    DRAFT      2014-03-31     Johnny Fan 
DESCRIPTION: First Draft. Generated by newclass.py
SCO/ERROR  : 
-------------------------------------------------------------------------------
*/
#include "product.config"
#ifdef HAS_EEPROM

#include "./EepromDrv_priv.h"
#include "trace.h"

/* Private functions / variables. Declare and drivers here */


/*****************************************************************************************************************
 *
 * Start-up / shut-down functions
 *
 *****************************************************************************************************************/
void EepromDrv_Ctor(cEepromDrv *me)
{
    ASSERT(me);
		/* set up the functions*/
    me->super_.SetValue = EepromDrv_WriteWords;
    me->super_.GetValue = EepromDrv_ReadWords;
}

void EepromDrv_Xtor(cEepromDrv *me)
{
    ASSERT(me);
}

/*****************************************************************************************************************
 *
 * Public functions
 *
 *****************************************************************************************************************/

/*****************************************************************************************************************
 *
 * private functions
 *
 *****************************************************************************************************************/

/* place the function here, not implemented yet*/


 /**
* Write some 32bit datas into EEPROM
*/
static bool EepromDrv_WriteWords(cStorageDrv *me, uint32 addr, uint32* data, uint32 sizeInBytes)
{
    cEepromDrv* pEepromObj;
    pEepromObj = (cEepromDrv*)me;
    return TRUE;
}

/**
* Read some 32bit datas from EEPROM
*/
static bool EepromDrv_ReadWords(cStorageDrv *me, uint32 addr, uint32* data, uint32 sizeInBytes)
{
    cEepromDrv* pEepromObj;
    pEepromObj = (cEepromDrv*)me;
    return TRUE;
}

#endif  // HAS_EEPROM