/*
-------------------------------------------------------------------------------
TYMPHANY LTD





                  Storage Driver
                  -------------------------

                  SW Module Document




@file        StorageDrv.c
@brief       It's the general storage driver
@author      Johnny Fan 
@date        2014-03-30
@copyright (c) Tymphany Ltd. All rights reserved.

Change History:
VERSION    : 1    DRAFT      2014-03-30     Johnny Fan 
DESCRIPTION: First Draft. Generated by newclass.py
SCO/ERROR  : 
-------------------------------------------------------------------------------
*/

#include "./StorageDrv_priv.h"
#include "NvmDrv.h"
#include "EepromDrv.h"
#include "trace.h"
/* Private functions / variables. Declare and drivers here */


/*****************************************************************************************************************
 *
 * Start-up / shut-down functions
 *
 *****************************************************************************************************************/
void StorageDrv_Ctor(cStorageDrv *me, const tStorageDevice* pStorageConfig)
{
    ASSERT(me && pStorageConfig);
    /* call different driver ctor function according to different device type */
    switch(pStorageConfig->deviceInfo.deviceType)
    {
#ifdef HAS_NVM
        case NVM_DEV_TYPE:
        {
            cNvmDrv* pNvmObj;
            pNvmObj = (cNvmDrv*) me;
            NvmDrv_Ctor(pNvmObj);
            break;
        }
#endif  // HAS_NVM
#ifdef HAS_EEPROM
        case EEPROM_TYPE:
        {
            cEepromDrv* pEepromObj;
            pEepromObj = (cEepromDrv*) me;
            EepromDrv_Ctor(pEepromObj);
            break;
        }    
#endif  // HAS_EEPROM
        default:
            break;
    }
}

void StorageDrv_Xtor(cStorageDrv *me)
{
    /* Fill me in! */
    ASSERT(me);
}

/*****************************************************************************************************************
 *
 * Public functions
 *
 *****************************************************************************************************************/

/*****************************************************************************************************************
 *
 * private functions
 *
 *****************************************************************************************************************/
