/*
 * File:           D:\working doc\CA22\dsp\ES1_debug\BnO_CA22_IC_1_PARAM.h
 *
 * Created:        Friday, September 29, 2017 9:56:52 AM
 * Description:    BnO_CA22_dsp_V0.0.1_i2c_debug:IC 1 parameter RAM definitions.
 *
 * This software is distributed in the hope that it will be useful,
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This software may only be used to program products purchased from
 * Analog Devices for incorporation by you into audio products that
 * are intended for resale to audio product end users. This software
 * may not be distributed whole or in any part to third parties.
 *
 * Copyright ©2017 Analog Devices, Inc. All rights reserved.
 */
#ifndef __BNO_CA22_IC_1_PARAM_H__
#define __BNO_CA22_IC_1_PARAM_H__


/* Module SafeLoadModule - SafeLoadModule*/
#define MOD_SAFELOADMODULE_COUNT                       7
#define MOD_SAFELOADMODULE_DEVICE                      "IC1"
#define MOD_SAFELOADMODULE_DATA_SAFELOAD0_ADDR         20
#define MOD_SAFELOADMODULE_DATA_SAFELOAD1_ADDR         21
#define MOD_SAFELOADMODULE_DATA_SAFELOAD2_ADDR         22
#define MOD_SAFELOADMODULE_DATA_SAFELOAD3_ADDR         23
#define MOD_SAFELOADMODULE_DATA_SAFELOAD4_ADDR         24
#define MOD_SAFELOADMODULE_ADDRESS_SAFELOAD_ADDR       25
#define MOD_SAFELOADMODULE_NUM_SAFELOAD_ADDR           26

/* Module Gen Filter4 - General Eq (2nd order)*/
#define MOD_TESTSIGNAL_GENFILTER4_COUNT                10
#define MOD_TESTSIGNAL_GENFILTER4_DEVICE               "IC1"
#define MOD_TESTSIGNAL_GENFILTER4_ALG0_STAGE0_B2_ADDR  27
#define MOD_TESTSIGNAL_GENFILTER4_ALG0_STAGE0_B2_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_TESTSIGNAL_GENFILTER4_ALG0_STAGE0_B2_TYPE  SIGMASTUDIOTYPE_8_24
#define MOD_TESTSIGNAL_GENFILTER4_ALG0_STAGE0_B1_ADDR  28
#define MOD_TESTSIGNAL_GENFILTER4_ALG0_STAGE0_B1_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_TESTSIGNAL_GENFILTER4_ALG0_STAGE0_B1_TYPE  SIGMASTUDIOTYPE_8_24
#define MOD_TESTSIGNAL_GENFILTER4_ALG0_STAGE0_B0_ADDR  29
#define MOD_TESTSIGNAL_GENFILTER4_ALG0_STAGE0_B0_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_TESTSIGNAL_GENFILTER4_ALG0_STAGE0_B0_TYPE  SIGMASTUDIOTYPE_8_24
#define MOD_TESTSIGNAL_GENFILTER4_ALG0_STAGE0_A2_ADDR  30
#define MOD_TESTSIGNAL_GENFILTER4_ALG0_STAGE0_A2_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_TESTSIGNAL_GENFILTER4_ALG0_STAGE0_A2_TYPE  SIGMASTUDIOTYPE_8_24
#define MOD_TESTSIGNAL_GENFILTER4_ALG0_STAGE0_A1_ADDR  31
#define MOD_TESTSIGNAL_GENFILTER4_ALG0_STAGE0_A1_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_TESTSIGNAL_GENFILTER4_ALG0_STAGE0_A1_TYPE  SIGMASTUDIOTYPE_8_24
#define MOD_TESTSIGNAL_GENFILTER4_ALG0_STAGE1_B2_ADDR  32
#define MOD_TESTSIGNAL_GENFILTER4_ALG0_STAGE1_B2_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(0.004445165283471)
#define MOD_TESTSIGNAL_GENFILTER4_ALG0_STAGE1_B2_TYPE  SIGMASTUDIOTYPE_8_24
#define MOD_TESTSIGNAL_GENFILTER4_ALG0_STAGE1_B1_ADDR  33
#define MOD_TESTSIGNAL_GENFILTER4_ALG0_STAGE1_B1_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(-0.4585033913469)
#define MOD_TESTSIGNAL_GENFILTER4_ALG0_STAGE1_B1_TYPE  SIGMASTUDIOTYPE_8_24
#define MOD_TESTSIGNAL_GENFILTER4_ALG0_STAGE1_B0_ADDR  34
#define MOD_TESTSIGNAL_GENFILTER4_ALG0_STAGE1_B0_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(0.7509201378235)
#define MOD_TESTSIGNAL_GENFILTER4_ALG0_STAGE1_B0_TYPE  SIGMASTUDIOTYPE_8_24
#define MOD_TESTSIGNAL_GENFILTER4_ALG0_STAGE1_A2_ADDR  35
#define MOD_TESTSIGNAL_GENFILTER4_ALG0_STAGE1_A2_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(-0.25352502746)
#define MOD_TESTSIGNAL_GENFILTER4_ALG0_STAGE1_A2_TYPE  SIGMASTUDIOTYPE_8_24
#define MOD_TESTSIGNAL_GENFILTER4_ALG0_STAGE1_A1_ADDR  36
#define MOD_TESTSIGNAL_GENFILTER4_ALG0_STAGE1_A1_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(1.10044246247)
#define MOD_TESTSIGNAL_GENFILTER4_ALG0_STAGE1_A1_TYPE  SIGMASTUDIOTYPE_8_24

/* Module HWSlew_Nx2 - Stereo Switch Nx2*/
#define MOD_SOURCESWITCH_HWSLEW_NX2_COUNT              3
#define MOD_SOURCESWITCH_HWSLEW_NX2_DEVICE             "IC1"
#define MOD_SOURCESWITCH_HWSLEW_NX2_ALG0_SLEW_MODE_ADDR 37
#define MOD_SOURCESWITCH_HWSLEW_NX2_ALG0_SLEW_MODE_FIXPT 0x0000208A
#define MOD_SOURCESWITCH_HWSLEW_NX2_ALG0_SLEW_MODE_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(8330)
#define MOD_SOURCESWITCH_HWSLEW_NX2_ALG0_SLEW_MODE_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_SOURCESWITCH_HWSLEW_NX2_ALG0_STEREOMUXSIGMA3002VOL00_ADDR 148
#define MOD_SOURCESWITCH_HWSLEW_NX2_ALG0_STEREOMUXSIGMA3002VOL00_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_SOURCESWITCH_HWSLEW_NX2_ALG0_STEREOMUXSIGMA3002VOL00_TYPE SIGMASTUDIOTYPE_8_24
#define MOD_SOURCESWITCH_HWSLEW_NX2_ALG0_STEREOMUXSIGMA3002VOL01_ADDR 149
#define MOD_SOURCESWITCH_HWSLEW_NX2_ALG0_STEREOMUXSIGMA3002VOL01_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_SOURCESWITCH_HWSLEW_NX2_ALG0_STEREOMUXSIGMA3002VOL01_TYPE SIGMASTUDIOTYPE_8_24

/* Module MasterMute - Mute*/
#define MOD_SOURCESWITCH_MASTERMUTE_COUNT              4
#define MOD_SOURCESWITCH_MASTERMUTE_DEVICE             "IC1"
#define MOD_SOURCESWITCH_MASTERMUTE_ALG0_SLEW_MODE_ADDR 39
#define MOD_SOURCESWITCH_MASTERMUTE_ALG0_SLEW_MODE_FIXPT 0x0000208A
#define MOD_SOURCESWITCH_MASTERMUTE_ALG0_SLEW_MODE_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(8330)
#define MOD_SOURCESWITCH_MASTERMUTE_ALG0_SLEW_MODE_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_SOURCESWITCH_MASTERMUTE_ALG0_MUTE_ADDR     40
#define MOD_SOURCESWITCH_MASTERMUTE_ALG0_MUTE_VALUE    SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_SOURCESWITCH_MASTERMUTE_ALG0_MUTE_TYPE     SIGMASTUDIOTYPE_8_24
#define MOD_SOURCESWITCH_MASTERMUTE_ALG1_SLEW_MODE_ADDR 42
#define MOD_SOURCESWITCH_MASTERMUTE_ALG1_SLEW_MODE_FIXPT 0x0000208A
#define MOD_SOURCESWITCH_MASTERMUTE_ALG1_SLEW_MODE_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(8330)
#define MOD_SOURCESWITCH_MASTERMUTE_ALG1_SLEW_MODE_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_SOURCESWITCH_MASTERMUTE_ALG1_MUTE_ADDR     43
#define MOD_SOURCESWITCH_MASTERMUTE_ALG1_MUTE_VALUE    SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_SOURCESWITCH_MASTERMUTE_ALG1_MUTE_TYPE     SIGMASTUDIOTYPE_8_24

/* Module Level1_3 - Single Level Detector w Numerical Display*/
#define MOD_TESTSIGNAL_LEVEL1_3_COUNT                  3
#define MOD_TESTSIGNAL_LEVEL1_3_DEVICE                 "IC1"
#define MOD_TESTSIGNAL_LEVEL1_3_ALG0_SINGLEBANDLEVELDETS3007TCONST_ADDR 44
#define MOD_TESTSIGNAL_LEVEL1_3_ALG0_SINGLEBANDLEVELDETS3007TCONST_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(0.00240140490349172)
#define MOD_TESTSIGNAL_LEVEL1_3_ALG0_SINGLEBANDLEVELDETS3007TCONST_TYPE SIGMASTUDIOTYPE_8_24
#define MOD_TESTSIGNAL_LEVEL1_3_ALG0_SINGLEBANDLEVELDETS3007HOLD_ADDR 45
#define MOD_TESTSIGNAL_LEVEL1_3_ALG0_SINGLEBANDLEVELDETS3007HOLD_FIXPT 0x000001E0
#define MOD_TESTSIGNAL_LEVEL1_3_ALG0_SINGLEBANDLEVELDETS3007HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(480)
#define MOD_TESTSIGNAL_LEVEL1_3_ALG0_SINGLEBANDLEVELDETS3007HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_TESTSIGNAL_LEVEL1_3_ALG0_SINGLEBANDLEVELDETS3007DECAY_ADDR 46
#define MOD_TESTSIGNAL_LEVEL1_3_ALG0_SINGLEBANDLEVELDETS3007DECAY_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(0.000217013888888889)
#define MOD_TESTSIGNAL_LEVEL1_3_ALG0_SINGLEBANDLEVELDETS3007DECAY_TYPE SIGMASTUDIOTYPE_8_24

/* Module Level1 - Single Level Detector w Numerical Display*/
#define MOD_LEVEL1_COUNT                               3
#define MOD_LEVEL1_DEVICE                              "IC1"
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETS3001TCONST_ADDR 58
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETS3001TCONST_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(0.00240140490349172)
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETS3001TCONST_TYPE SIGMASTUDIOTYPE_8_24
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETS3001HOLD_ADDR 59
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETS3001HOLD_FIXPT 0x000001E0
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETS3001HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(480)
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETS3001HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETS3001DECAY_ADDR 60
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETS3001DECAY_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(0.000217013888888889)
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETS3001DECAY_TYPE SIGMASTUDIOTYPE_8_24

/* Module Level1_2 - Single Level Detector w Numerical Display*/
#define MOD_LEVEL1_2_COUNT                             3
#define MOD_LEVEL1_2_DEVICE                            "IC1"
#define MOD_LEVEL1_2_ALG0_SINGLEBANDLEVELDETS3006TCONST_ADDR 72
#define MOD_LEVEL1_2_ALG0_SINGLEBANDLEVELDETS3006TCONST_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(0.00240140490349172)
#define MOD_LEVEL1_2_ALG0_SINGLEBANDLEVELDETS3006TCONST_TYPE SIGMASTUDIOTYPE_8_24
#define MOD_LEVEL1_2_ALG0_SINGLEBANDLEVELDETS3006HOLD_ADDR 73
#define MOD_LEVEL1_2_ALG0_SINGLEBANDLEVELDETS3006HOLD_FIXPT 0x000001E0
#define MOD_LEVEL1_2_ALG0_SINGLEBANDLEVELDETS3006HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(480)
#define MOD_LEVEL1_2_ALG0_SINGLEBANDLEVELDETS3006HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_LEVEL1_2_ALG0_SINGLEBANDLEVELDETS3006DECAY_ADDR 74
#define MOD_LEVEL1_2_ALG0_SINGLEBANDLEVELDETS3006DECAY_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(0.000217013888888889)
#define MOD_LEVEL1_2_ALG0_SINGLEBANDLEVELDETS3006DECAY_TYPE SIGMASTUDIOTYPE_8_24

/* Module BypassGain - Single Volume*/
#define MOD_BYPASSSWITCH_BYPASSGAIN_COUNT              2
#define MOD_BYPASSSWITCH_BYPASSGAIN_DEVICE             "IC1"
#define MOD_BYPASSSWITCH_BYPASSGAIN_ALG0_TARGET_ADDR   87
#define MOD_BYPASSSWITCH_BYPASSGAIN_ALG0_TARGET_VALUE  SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_BYPASSSWITCH_BYPASSGAIN_ALG0_TARGET_TYPE   SIGMASTUDIOTYPE_8_24
#define MOD_BYPASSSWITCH_BYPASSGAIN_ALG0_SLEW_MODE_ADDR 88
#define MOD_BYPASSSWITCH_BYPASSGAIN_ALG0_SLEW_MODE_FIXPT 0x0000208A
#define MOD_BYPASSSWITCH_BYPASSGAIN_ALG0_SLEW_MODE_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(8330)
#define MOD_BYPASSSWITCH_BYPASSGAIN_ALG0_SLEW_MODE_TYPE SIGMASTUDIOTYPE_INTEGER

/* Module MasterVolume - Single Volume*/
#define MOD_VOLUMECONTROL_MASTERVOLUME_COUNT           2
#define MOD_VOLUMECONTROL_MASTERVOLUME_DEVICE          "IC1"
#define MOD_VOLUMECONTROL_MASTERVOLUME_ALG0_TARGET_ADDR 90
#define MOD_VOLUMECONTROL_MASTERVOLUME_ALG0_TARGET_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_VOLUMECONTROL_MASTERVOLUME_ALG0_TARGET_TYPE SIGMASTUDIOTYPE_8_24
#define MOD_VOLUMECONTROL_MASTERVOLUME_ALG0_SLEW_MODE_ADDR 91
#define MOD_VOLUMECONTROL_MASTERVOLUME_ALG0_SLEW_MODE_FIXPT 0x0000208A
#define MOD_VOLUMECONTROL_MASTERVOLUME_ALG0_SLEW_MODE_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(8330)
#define MOD_VOLUMECONTROL_MASTERVOLUME_ALG0_SLEW_MODE_TYPE SIGMASTUDIOTYPE_INTEGER

/* Module LevelDet_LeftCH - Single Level Detector w Numerical Display*/
#define MOD_SYSTEMTUNING_LEVELDET_LEFTCH_COUNT         3
#define MOD_SYSTEMTUNING_LEVELDET_LEFTCH_DEVICE        "IC1"
#define MOD_SYSTEMTUNING_LEVELDET_LEFTCH_ALG0_SINGLEBANDLEVELDETS3002TCONST_ADDR 92
#define MOD_SYSTEMTUNING_LEVELDET_LEFTCH_ALG0_SINGLEBANDLEVELDETS3002TCONST_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(0.00240140490349172)
#define MOD_SYSTEMTUNING_LEVELDET_LEFTCH_ALG0_SINGLEBANDLEVELDETS3002TCONST_TYPE SIGMASTUDIOTYPE_8_24
#define MOD_SYSTEMTUNING_LEVELDET_LEFTCH_ALG0_SINGLEBANDLEVELDETS3002HOLD_ADDR 93
#define MOD_SYSTEMTUNING_LEVELDET_LEFTCH_ALG0_SINGLEBANDLEVELDETS3002HOLD_FIXPT 0x000001E0
#define MOD_SYSTEMTUNING_LEVELDET_LEFTCH_ALG0_SINGLEBANDLEVELDETS3002HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(480)
#define MOD_SYSTEMTUNING_LEVELDET_LEFTCH_ALG0_SINGLEBANDLEVELDETS3002HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_SYSTEMTUNING_LEVELDET_LEFTCH_ALG0_SINGLEBANDLEVELDETS3002DECAY_ADDR 94
#define MOD_SYSTEMTUNING_LEVELDET_LEFTCH_ALG0_SINGLEBANDLEVELDETS3002DECAY_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(0.000217013888888889)
#define MOD_SYSTEMTUNING_LEVELDET_LEFTCH_ALG0_SINGLEBANDLEVELDETS3002DECAY_TYPE SIGMASTUDIOTYPE_8_24

/* Module LevelDet_RightCh - Single Level Detector w Numerical Display*/
#define MOD_SYSTEMTUNING_LEVELDET_RIGHTCH_COUNT        3
#define MOD_SYSTEMTUNING_LEVELDET_RIGHTCH_DEVICE       "IC1"
#define MOD_SYSTEMTUNING_LEVELDET_RIGHTCH_ALG0_SINGLEBANDLEVELDETS3003TCONST_ADDR 106
#define MOD_SYSTEMTUNING_LEVELDET_RIGHTCH_ALG0_SINGLEBANDLEVELDETS3003TCONST_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(0.00240140490349172)
#define MOD_SYSTEMTUNING_LEVELDET_RIGHTCH_ALG0_SINGLEBANDLEVELDETS3003TCONST_TYPE SIGMASTUDIOTYPE_8_24
#define MOD_SYSTEMTUNING_LEVELDET_RIGHTCH_ALG0_SINGLEBANDLEVELDETS3003HOLD_ADDR 107
#define MOD_SYSTEMTUNING_LEVELDET_RIGHTCH_ALG0_SINGLEBANDLEVELDETS3003HOLD_FIXPT 0x000001E0
#define MOD_SYSTEMTUNING_LEVELDET_RIGHTCH_ALG0_SINGLEBANDLEVELDETS3003HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(480)
#define MOD_SYSTEMTUNING_LEVELDET_RIGHTCH_ALG0_SINGLEBANDLEVELDETS3003HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_SYSTEMTUNING_LEVELDET_RIGHTCH_ALG0_SINGLEBANDLEVELDETS3003DECAY_ADDR 108
#define MOD_SYSTEMTUNING_LEVELDET_RIGHTCH_ALG0_SINGLEBANDLEVELDETS3003DECAY_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(0.000217013888888889)
#define MOD_SYSTEMTUNING_LEVELDET_RIGHTCH_ALG0_SINGLEBANDLEVELDETS3003DECAY_TYPE SIGMASTUDIOTYPE_8_24

/* Module LevelDet_WooferOutput - Single Level Detector w Numerical Display*/
#define MOD_SYSTEMTUNING_LEVELDET_WOOFEROUTPUT_COUNT   3
#define MOD_SYSTEMTUNING_LEVELDET_WOOFEROUTPUT_DEVICE  "IC1"
#define MOD_SYSTEMTUNING_LEVELDET_WOOFEROUTPUT_ALG0_SINGLEBANDLEVELDETS3004TCONST_ADDR 120
#define MOD_SYSTEMTUNING_LEVELDET_WOOFEROUTPUT_ALG0_SINGLEBANDLEVELDETS3004TCONST_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(0.00240140490349172)
#define MOD_SYSTEMTUNING_LEVELDET_WOOFEROUTPUT_ALG0_SINGLEBANDLEVELDETS3004TCONST_TYPE SIGMASTUDIOTYPE_8_24
#define MOD_SYSTEMTUNING_LEVELDET_WOOFEROUTPUT_ALG0_SINGLEBANDLEVELDETS3004HOLD_ADDR 121
#define MOD_SYSTEMTUNING_LEVELDET_WOOFEROUTPUT_ALG0_SINGLEBANDLEVELDETS3004HOLD_FIXPT 0x000001E0
#define MOD_SYSTEMTUNING_LEVELDET_WOOFEROUTPUT_ALG0_SINGLEBANDLEVELDETS3004HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(480)
#define MOD_SYSTEMTUNING_LEVELDET_WOOFEROUTPUT_ALG0_SINGLEBANDLEVELDETS3004HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_SYSTEMTUNING_LEVELDET_WOOFEROUTPUT_ALG0_SINGLEBANDLEVELDETS3004DECAY_ADDR 122
#define MOD_SYSTEMTUNING_LEVELDET_WOOFEROUTPUT_ALG0_SINGLEBANDLEVELDETS3004DECAY_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(0.000217013888888889)
#define MOD_SYSTEMTUNING_LEVELDET_WOOFEROUTPUT_ALG0_SINGLEBANDLEVELDETS3004DECAY_TYPE SIGMASTUDIOTYPE_8_24

/* Module LevelDet_TweeterOutput - Single Level Detector w Numerical Display*/
#define MOD_SYSTEMTUNING_LEVELDET_TWEETEROUTPUT_COUNT  3
#define MOD_SYSTEMTUNING_LEVELDET_TWEETEROUTPUT_DEVICE "IC1"
#define MOD_SYSTEMTUNING_LEVELDET_TWEETEROUTPUT_ALG0_SINGLEBANDLEVELDETS3005TCONST_ADDR 134
#define MOD_SYSTEMTUNING_LEVELDET_TWEETEROUTPUT_ALG0_SINGLEBANDLEVELDETS3005TCONST_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(0.00240140490349172)
#define MOD_SYSTEMTUNING_LEVELDET_TWEETEROUTPUT_ALG0_SINGLEBANDLEVELDETS3005TCONST_TYPE SIGMASTUDIOTYPE_8_24
#define MOD_SYSTEMTUNING_LEVELDET_TWEETEROUTPUT_ALG0_SINGLEBANDLEVELDETS3005HOLD_ADDR 135
#define MOD_SYSTEMTUNING_LEVELDET_TWEETEROUTPUT_ALG0_SINGLEBANDLEVELDETS3005HOLD_FIXPT 0x000001E0
#define MOD_SYSTEMTUNING_LEVELDET_TWEETEROUTPUT_ALG0_SINGLEBANDLEVELDETS3005HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(480)
#define MOD_SYSTEMTUNING_LEVELDET_TWEETEROUTPUT_ALG0_SINGLEBANDLEVELDETS3005HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_SYSTEMTUNING_LEVELDET_TWEETEROUTPUT_ALG0_SINGLEBANDLEVELDETS3005DECAY_ADDR 136
#define MOD_SYSTEMTUNING_LEVELDET_TWEETEROUTPUT_ALG0_SINGLEBANDLEVELDETS3005DECAY_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(0.000217013888888889)
#define MOD_SYSTEMTUNING_LEVELDET_TWEETEROUTPUT_ALG0_SINGLEBANDLEVELDETS3005DECAY_TYPE SIGMASTUDIOTYPE_8_24

/* Module W_Noise - White Noise*/
#define MOD_TESTSIGNAL_W_NOISE_COUNT                   1
#define MOD_TESTSIGNAL_W_NOISE_DEVICE                  "IC1"
#define MOD_TESTSIGNAL_W_NOISE_ENABLENOISE_ADDR        152
#define MOD_TESTSIGNAL_W_NOISE_ENABLENOISE_VALUE       SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_TESTSIGNAL_W_NOISE_ENABLENOISE_TYPE        SIGMASTUDIOTYPE_8_24

/* Module Version - DC Input Entry*/
#define MOD_VERSION_COUNT                              1
#define MOD_VERSION_DEVICE                             "IC1"
#define MOD_VERSION_DCINPALG145X1VALUE_ADDR            153
#define MOD_VERSION_DCINPALG145X1VALUE_FIXPT           0x00000001
#define MOD_VERSION_DCINPALG145X1VALUE_VALUE           SIGMASTUDIOTYPE_INTEGER_CONVERT(1)
#define MOD_VERSION_DCINPALG145X1VALUE_TYPE            SIGMASTUDIOTYPE_INTEGER

/* Module Gain15 - Linear Gain*/
#define MOD_TESTSIGNAL_GAIN15_COUNT                    1
#define MOD_TESTSIGNAL_GAIN15_DEVICE                   "IC1"
#define MOD_TESTSIGNAL_GAIN15_GAINALGNS145X6GAIN_ADDR  154
#define MOD_TESTSIGNAL_GAIN15_GAINALGNS145X6GAIN_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(0.5)
#define MOD_TESTSIGNAL_GAIN15_GAINALGNS145X6GAIN_TYPE  SIGMASTUDIOTYPE_8_24

/* Module TestSignal_Switch - Stereo Switch Nx2*/
#define MOD_TESTSIGNAL_TESTSIGNAL_SWITCH_COUNT         1
#define MOD_TESTSIGNAL_TESTSIGNAL_SWITCH_DEVICE        "IC1"
#define MOD_TESTSIGNAL_TESTSIGNAL_SWITCH_STEREOMUXSIGMA300NS1INDEX_ADDR 155
#define MOD_TESTSIGNAL_TESTSIGNAL_SWITCH_STEREOMUXSIGMA300NS1INDEX_FIXPT 0x00000000
#define MOD_TESTSIGNAL_TESTSIGNAL_SWITCH_STEREOMUXSIGMA300NS1INDEX_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_TESTSIGNAL_TESTSIGNAL_SWITCH_STEREOMUXSIGMA300NS1INDEX_TYPE SIGMASTUDIOTYPE_INTEGER

/* Module BP_Switch - Multi CH Switch Nx8*/
#define MOD_BYPASSSWITCH_BP_SWITCH_COUNT               1
#define MOD_BYPASSSWITCH_BP_SWITCH_DEVICE              "IC1"
#define MOD_BYPASSSWITCH_BP_SWITCH_STEREOMUXSIGMA300NS81INDEX_ADDR 156
#define MOD_BYPASSSWITCH_BP_SWITCH_STEREOMUXSIGMA300NS81INDEX_FIXPT 0x00000000
#define MOD_BYPASSSWITCH_BP_SWITCH_STEREOMUXSIGMA300NS81INDEX_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_BYPASSSWITCH_BP_SWITCH_STEREOMUXSIGMA300NS81INDEX_TYPE SIGMASTUDIOTYPE_INTEGER

/* Module Mute1_W - Mute*/
#define MOD_MUTE1_W_COUNT                              1
#define MOD_MUTE1_W_DEVICE                             "IC1"
#define MOD_MUTE1_W_MUTENOSLEWADAU145XALG1MUTE_ADDR    157
#define MOD_MUTE1_W_MUTENOSLEWADAU145XALG1MUTE_FIXPT   0x00000001
#define MOD_MUTE1_W_MUTENOSLEWADAU145XALG1MUTE_VALUE   SIGMASTUDIOTYPE_INTEGER_CONVERT(1)
#define MOD_MUTE1_W_MUTENOSLEWADAU145XALG1MUTE_TYPE    SIGMASTUDIOTYPE_INTEGER

/* Module Mute1_T - Mute*/
#define MOD_MUTE1_T_COUNT                              1
#define MOD_MUTE1_T_DEVICE                             "IC1"
#define MOD_MUTE1_T_MUTENOSLEWADAU145XALG2MUTE_ADDR    158
#define MOD_MUTE1_T_MUTENOSLEWADAU145XALG2MUTE_FIXPT   0x00000001
#define MOD_MUTE1_T_MUTENOSLEWADAU145XALG2MUTE_VALUE   SIGMASTUDIOTYPE_INTEGER_CONVERT(1)
#define MOD_MUTE1_T_MUTENOSLEWADAU145XALG2MUTE_TYPE    SIGMASTUDIOTYPE_INTEGER

/* Module Mute2_W - Mute*/
#define MOD_MUTE2_W_COUNT                              1
#define MOD_MUTE2_W_DEVICE                             "IC1"
#define MOD_MUTE2_W_MUTENOSLEWADAU145XALG3MUTE_ADDR    159
#define MOD_MUTE2_W_MUTENOSLEWADAU145XALG3MUTE_FIXPT   0x00000001
#define MOD_MUTE2_W_MUTENOSLEWADAU145XALG3MUTE_VALUE   SIGMASTUDIOTYPE_INTEGER_CONVERT(1)
#define MOD_MUTE2_W_MUTENOSLEWADAU145XALG3MUTE_TYPE    SIGMASTUDIOTYPE_INTEGER

/* Module Mute2_T - Mute*/
#define MOD_MUTE2_T_COUNT                              1
#define MOD_MUTE2_T_DEVICE                             "IC1"
#define MOD_MUTE2_T_MUTENOSLEWADAU145XALG4MUTE_ADDR    160
#define MOD_MUTE2_T_MUTENOSLEWADAU145XALG4MUTE_FIXPT   0x00000001
#define MOD_MUTE2_T_MUTENOSLEWADAU145XALG4MUTE_VALUE   SIGMASTUDIOTYPE_INTEGER_CONVERT(1)
#define MOD_MUTE2_T_MUTENOSLEWADAU145XALG4MUTE_TYPE    SIGMASTUDIOTYPE_INTEGER

/* Module Mute3_W - Mute*/
#define MOD_MUTE3_W_COUNT                              1
#define MOD_MUTE3_W_DEVICE                             "IC1"
#define MOD_MUTE3_W_MUTENOSLEWADAU145XALG5MUTE_ADDR    161
#define MOD_MUTE3_W_MUTENOSLEWADAU145XALG5MUTE_FIXPT   0x00000001
#define MOD_MUTE3_W_MUTENOSLEWADAU145XALG5MUTE_VALUE   SIGMASTUDIOTYPE_INTEGER_CONVERT(1)
#define MOD_MUTE3_W_MUTENOSLEWADAU145XALG5MUTE_TYPE    SIGMASTUDIOTYPE_INTEGER

/* Module Mute3_T - Mute*/
#define MOD_MUTE3_T_COUNT                              1
#define MOD_MUTE3_T_DEVICE                             "IC1"
#define MOD_MUTE3_T_MUTENOSLEWADAU145XALG6MUTE_ADDR    162
#define MOD_MUTE3_T_MUTENOSLEWADAU145XALG6MUTE_FIXPT   0x00000001
#define MOD_MUTE3_T_MUTENOSLEWADAU145XALG6MUTE_VALUE   SIGMASTUDIOTYPE_INTEGER_CONVERT(1)
#define MOD_MUTE3_T_MUTENOSLEWADAU145XALG6MUTE_TYPE    SIGMASTUDIOTYPE_INTEGER

/* Module Mute4_W - Mute*/
#define MOD_MUTE4_W_COUNT                              1
#define MOD_MUTE4_W_DEVICE                             "IC1"
#define MOD_MUTE4_W_MUTENOSLEWADAU145XALG7MUTE_ADDR    163
#define MOD_MUTE4_W_MUTENOSLEWADAU145XALG7MUTE_FIXPT   0x00000001
#define MOD_MUTE4_W_MUTENOSLEWADAU145XALG7MUTE_VALUE   SIGMASTUDIOTYPE_INTEGER_CONVERT(1)
#define MOD_MUTE4_W_MUTENOSLEWADAU145XALG7MUTE_TYPE    SIGMASTUDIOTYPE_INTEGER

/* Module Mute4_T - Mute*/
#define MOD_MUTE4_T_COUNT                              1
#define MOD_MUTE4_T_DEVICE                             "IC1"
#define MOD_MUTE4_T_MUTENOSLEWADAU145XALG8MUTE_ADDR    164
#define MOD_MUTE4_T_MUTENOSLEWADAU145XALG8MUTE_FIXPT   0x00000001
#define MOD_MUTE4_T_MUTENOSLEWADAU145XALG8MUTE_VALUE   SIGMASTUDIOTYPE_INTEGER_CONVERT(1)
#define MOD_MUTE4_T_MUTENOSLEWADAU145XALG8MUTE_TYPE    SIGMASTUDIOTYPE_INTEGER

#endif
