#ifndef SETTING_ID_H
#define SETTING_ID_H

typedef enum
{
    SETID_START = 0,
    SETID_AUDIO_SOURCE = SETID_START,
    SETID_VOLUME,
    SETID_TREBLE,
    SETID_BASS,
    SETID_BT_STATUS,
    SETID_PDL_EMPTY,
    SETID_SHAPE_EQ,
    SETID_MAX
}eSettingId;

#endif
