#ifndef _ADAU1451_CONFIG_
#define _ADAU1451_CONFIG_

/************************************************************************
**********  INCLUDE                                            **********
************************************************************************/
typedef const uint8 ADI_REG_TYPE; //must before include file
#include "ADAU1451_IC_1_PARAM.h" 
#include "ADAU1451_IC_1.h"


/************************************************************************
**********  MACRO                                              **********
************************************************************************/
#define  DSP_RESET_PIN_HIGH() GpioDrv_SetBit(&gpioDsp,GPIO_OUT_DSP_RST_N) //** Active LOW **
#define  DSP_RESET_PIN_LOW()  GpioDrv_ClearBit(&gpioDsp,GPIO_OUT_DSP_RST_N)
#define  IS_DSP_TUNE()        GpioDrv_ReadBit(&gpioDsp,GPIO_IN_DSP_TUNE)



/************************************************************************
**********  PORTING LAYDER                                     **********
************************************************************************/
#define SIGMA_WRITE_REGISTER_BLOCK(dev_address, reg_addr, data_len, pdata) \
    DSPDrv1451_Writer_Register(me, dev_address, reg_addr, data_len, (uint8*)pdata);



/************************************************************************
********** Messages related to the "DSP Core Control Register" **********
************************************************************************/
/* Common */
#define ADAU1451_REGISTER_LEN       (4)
#define PROGRAM_RAM_PAGE_SIZE       (4)
#define PARA_RAM_PAGE_SIZE          (4)
#define DM1_PAGE_SIZE               (4)

/* Signal Detection */
#define ADAU1451_SIGNAL_DETECTION_LEN       (4)
#define ADAU1451_SIGNAL_DETECTION_ADDR      MOD_SIGNALDETECTION_READBACK_SIGDET_READBACKALGSIGMA3002_ADDR
#define ADAU1451_SPDIF_IN_SIGNAL_DETECTION_ADDR      MOD_SIGNALDETECTION_READBACK_SIGDET_2_READBACKALGSIGMA3005_ADDR
#define ADAU1451_AUXIN_SIGNAL_DETECTION_ADDR      MOD_SIGNALDETECTION_READBACK_SIGDET_3_READBACKALGSIGMA3006_ADDR


/* Volume Setting */
#define ADAU1451_UPDATE_VOLUME_LEN          (6)
#define ADAU1451_VOLUME_ADDR                MOD_VOLUMECONTROL_DC1_2_DCINPALG145X2VALUE_ADDR

/* Source selection 
 * the register for source selection is changed when the DSP layout is changed
 * so the complier switch is here
 */
#define SOURCE_SELECT_REGISTER_HIGH_BYTE    (MOD_SOURCESWITCH_NX2_1_ALG0_STEREOMUXSIGMA3001VOL00_ADDR >> 8)
#define SOURCE_SELECT_REGISTER_LOW_BYTE     (MOD_SOURCESWITCH_NX2_1_ALG0_STEREOMUXSIGMA3001VOL00_ADDR & 0xff)
#define SOURCE_SELECT_REGISTER_LEN          (14)

const uint8 ADAU1451_DIGITAL_INPUT_1_SELECT[SOURCE_SELECT_REGISTER_LEN]  = {SOURCE_SELECT_REGISTER_HIGH_BYTE, SOURCE_SELECT_REGISTER_LOW_BYTE,
                                                  0x01, 0x00, 0x00, 0x00,
                                                  0x00, 0x00, 0x00, 0x00,
                                                  0x00, 0x00, 0x00, 0x00};
const uint8 ADAU1451_DIGITAL_INPUT_2_SELECT[SOURCE_SELECT_REGISTER_LEN]  = {SOURCE_SELECT_REGISTER_HIGH_BYTE, SOURCE_SELECT_REGISTER_LOW_BYTE,
                                                  0x00, 0x00, 0x00, 0x00,
                                                  0x00, 0x00, 0x00, 0x00,
                                                  0x01, 0x00, 0x00, 0x00};
const uint8 ADAU1451_DIGITAL_INPUT_SPDIF_SELECT[SOURCE_SELECT_REGISTER_LEN]  = {SOURCE_SELECT_REGISTER_HIGH_BYTE, SOURCE_SELECT_REGISTER_LOW_BYTE,
                                                  0x00, 0x00, 0x00, 0x00,
                                                  0x01, 0x00, 0x00, 0x00,
                                                  0x00, 0x00, 0x00, 0x00};


/* NTC tempearture update */
#define DC_REGISTER_LEN     (6)

/* Line-in Multi-room source selection 
 * the register for Lne-in Multi-room source selection is changed when the DSP layout is changed
 * so the complier switch is here
 */
#define LINE_IN_SOURCE_SELECT_REGISTER_HIGH_BYTE    (MOD_NX2_3_ALG0_STEREOMUXSIGMA3004VOL00_ADDR >> 8)
#define LINE_IN_SOURCE_SELECT_REGISTER_LOW_BYTE     (MOD_NX2_3_ALG0_STEREOMUXSIGMA3004VOL00_ADDR & 0xff)
#define LINE_IN_SOURCE_SELECT_REGISTER_LEN          (10)

const uint8 ADAU1451_LINE_IN_1_SELECT[LINE_IN_SOURCE_SELECT_REGISTER_LEN]  = {LINE_IN_SOURCE_SELECT_REGISTER_HIGH_BYTE, LINE_IN_SOURCE_SELECT_REGISTER_LOW_BYTE,
                                                  0x01, 0x00, 0x00, 0x00,
                                                  0x00, 0x00, 0x00, 0x00};
const uint8 ADAU1451_LINE_IN_2_SELECT[LINE_IN_SOURCE_SELECT_REGISTER_LEN]  = {LINE_IN_SOURCE_SELECT_REGISTER_HIGH_BYTE, LINE_IN_SOURCE_SELECT_REGISTER_LOW_BYTE,
                                                  0x00, 0x00, 0x00, 0x00,
                                                  0x01, 0x00, 0x00, 0x00};

/*
* Line-in Mute
*/
#define LINE_IN_TO_ASETK_MUTE_REGISTER_HIGH_BYTE    (MOD_LINEINMUTE_ALG0_MUTE_ADDR >> 8)
#define LINE_IN_TO_ASETK_MUTE_REGISTER_LOW_BYTE     (MOD_LINEINMUTE_ALG0_MUTE_ADDR & 0xff)
#define LINE_IN_TO_ASETK_MUTE_REGISTER_LEN          (6)

const uint8 ADAU1451_LINE_IN_TO_ASETK_MUTE_ENABLE[LINE_IN_TO_ASETK_MUTE_REGISTER_LEN]  = {LINE_IN_TO_ASETK_MUTE_REGISTER_HIGH_BYTE, LINE_IN_TO_ASETK_MUTE_REGISTER_LOW_BYTE,
                                                  0x00, 0x00, 0x00, 0x00};
const uint8 ADAU1451_LINE_IN_TO_ASETK_MUTE_DISABLE[LINE_IN_TO_ASETK_MUTE_REGISTER_LEN] = {LINE_IN_TO_ASETK_MUTE_REGISTER_HIGH_BYTE, LINE_IN_TO_ASETK_MUTE_REGISTER_LOW_BYTE,
                                                  0x01, 0x00, 0x00, 0x00};

/*
* Line-in sensitivity
*/
#define LINE_IN_SENSITIVITY_REGISTER_HIGH_BYTE    (MOD_LINEINSENSITIVITY_GAINALGNS145X7GAIN_ADDR >> 8)
#define LINE_IN_SENSITIVITY_REGISTER_LOW_BYTE     (MOD_LINEINSENSITIVITY_GAINALGNS145X7GAIN_ADDR & 0xff)
#define LINE_IN_SENSITIVITY_REGISTER_LEN          (6)

/* High: 0 dB */
const uint8 ADAU1451_LINE_IN_SENSITIVITY_HIGH[LINE_IN_SENSITIVITY_REGISTER_LEN]  = {LINE_IN_SENSITIVITY_REGISTER_HIGH_BYTE, LINE_IN_SENSITIVITY_REGISTER_LOW_BYTE,
                                                  0x01, 0x00, 0x00, 0x00};
/* Medium: -3 dB */
const uint8 ADAU1451_LINE_IN_SENSITIVITY_MEDIUM[LINE_IN_SENSITIVITY_REGISTER_LEN] = {LINE_IN_SENSITIVITY_REGISTER_HIGH_BYTE, LINE_IN_SENSITIVITY_REGISTER_LOW_BYTE,
                                                  0x00, 0xB5, 0x3B, 0xEF};
/* Low: -6 dB */
const uint8 ADAU1451_LINE_IN_SENSITIVITY_LOW[LINE_IN_SENSITIVITY_REGISTER_LEN]  = {LINE_IN_SENSITIVITY_REGISTER_HIGH_BYTE, LINE_IN_SENSITIVITY_REGISTER_LOW_BYTE,
                                                  0x00, 0x80, 0x4D, 0xCE};
/* Disable: 0 dB */
const uint8 ADAU1451_LINE_IN_SENSITIVITY_DISABLE[LINE_IN_SENSITIVITY_REGISTER_LEN] = {LINE_IN_SENSITIVITY_REGISTER_HIGH_BYTE, LINE_IN_SENSITIVITY_REGISTER_LOW_BYTE,
                                                  0x01, 0x00, 0x00, 0x00};

/* Pass through enable */
#define PASS_THROUGH_REGISTER_HIGH_BYTE    (MOD_BYPASS_NX6_1_STEREOMUXSIGMA300NS61INDEX_ADDR >> 8)
#define PASS_THROUGH_REGISTER_LOW_BYTE     (MOD_BYPASS_NX6_1_STEREOMUXSIGMA300NS61INDEX_ADDR & 0xff)
#define PASS_THROUGH_REGISTER_LEN          (6)

const uint8 ADAU1451_PASS_THROUGH_ENABLE[PASS_THROUGH_REGISTER_LEN]  = {PASS_THROUGH_REGISTER_HIGH_BYTE, PASS_THROUGH_REGISTER_LOW_BYTE,
                                                  0x00, 0x00, 0x00, 0x06};
const uint8 ADAU1451_PASS_THROUGH_DISABLE[PASS_THROUGH_REGISTER_LEN] = {PASS_THROUGH_REGISTER_HIGH_BYTE, PASS_THROUGH_REGISTER_LOW_BYTE,
                                                  0x00, 0x00, 0x00, 0x00};


/* DSP Version */
#define DSP_VER_REGISTER              (MOD_DC1_DCINPALG145X1VALUE_ADDR)
#define DSP_VER_REGISTER_LEN          (4)

/* ASRC */
#define DSP_ASRC_FROM_ASETK  DSP_ASRC0


/***********************************************************/
/****************** Global Variable ************************/
/***********************************************************/

static tDspInitSection DspInitSection[] =
{
    {DSPDrv1451_Reset1, 50},
    {DSPDrv1451_Reset2, 50},
    {DSPDrv1451_Reset3, 50},
    {&DSPDrv1451_InitI2c, 10},
    {&DSPDrv1451_InitSection1, 10},
    {&DSPDrv1451_InitSection2, 10},
    {&DSPDrv1451_InitSection3, 10},
    {&DSPDrv1451_InitSection4, 10},
    {&DSPDrv1451_InitSection5, 50},
    {&DSPDrv1451_InitSection6, 50},
    {&DSPDrv1451_InitSection7, 50},
    {&DSPDrv1451_InitSection8, 10},
    {&DSPDrv1451_InitSection9, 10}
};

/************************************************************************
**********  INIT FUNCTION                                      **********
************************************************************************/
/* When export files from ADAU1451.dspproj, remember to porting 
 * initialize function from ADAU1451_IC_1.h
 */
static void DSPDrv1451_InitSection1(void *p)
{
    TP_PRINTF("DSPDrv1451_InitSection1\n\r");

    cDSPDrv1451* me = (cDSPDrv1451*)p;
    SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOFT_RESET_IC_1_ADDR, REG_SOFT_RESET_IC_1_BYTE, R0_SOFT_RESET_IC_1_Default );
    SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOFT_RESET_IC_1_ADDR, REG_SOFT_RESET_IC_1_BYTE, R1_SOFT_RESET_IC_1_Default );
    //SIGMA_WRITE_DELAY( DEVICE_ADDR_IC_1, R2_RESET_DELAY_IC_1_SIZE, R2_RESET_DELAY_IC_1_Default );

    TP_PRINTF("DSPDrv1451_InitSection1 finish\n\r");
}

static void DSPDrv1451_InitSection2(void *p)
{
    TP_PRINTF("DSPDrv1451_InitSection2\n\r");

    cDSPDrv1451* me = (cDSPDrv1451*)p;
    SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_HIBERNATE_IC_1_ADDR, REG_HIBERNATE_IC_1_BYTE, R3_HIBERNATE_IC_1_Default );
    SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_HIBERNATE_IC_1_ADDR, REG_HIBERNATE_IC_1_BYTE, R4_HIBERNATE_IC_1_Default );
    //SIGMA_WRITE_DELAY( DEVICE_ADDR_IC_1, R5_HIBERNATE_DELAY_IC_1_SIZE, R5_HIBERNATE_DELAY_IC_1_Default );

    TP_PRINTF("DSPDrv1451_InitSection2 finish\n\r");
}

static void DSPDrv1451_InitSection3(void *p)
{
    TP_PRINTF("DSPDrv1451_InitSection3\n\r");

    cDSPDrv1451* me = (cDSPDrv1451*)p;    
    SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_KILL_CORE_IC_1_ADDR, REG_KILL_CORE_IC_1_BYTE, R6_KILL_CORE_IC_1_Default );
    SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_KILL_CORE_IC_1_ADDR, REG_KILL_CORE_IC_1_BYTE, R7_KILL_CORE_IC_1_Default );
    SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_PLL_ENABLE_IC_1_ADDR, REG_PLL_ENABLE_IC_1_BYTE, R8_PLL_ENABLE_IC_1_Default );
    SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_PLL_CTRL1_IC_1_ADDR, REG_PLL_CTRL1_IC_1_BYTE, R9_PLL_CTRL1_IC_1_Default );
    SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_PLL_CLK_SRC_IC_1_ADDR, REG_PLL_CLK_SRC_IC_1_BYTE, R10_PLL_CLK_SRC_IC_1_Default );
    SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_MCLK_OUT_IC_1_ADDR, REG_MCLK_OUT_IC_1_BYTE, R11_MCLK_OUT_IC_1_Default );
    SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_PLL_ENABLE_IC_1_ADDR, REG_PLL_ENABLE_IC_1_BYTE, R12_PLL_ENABLE_IC_1_Default );
    //SIGMA_WRITE_DELAY( DEVICE_ADDR_IC_1, R13_PLL_LOCK_DELAY_IC_1_SIZE, R13_PLL_LOCK_DELAY_IC_1_Default );

    TP_PRINTF("DSPDrv1451_InitSection3 finish\n\r");
}

static void DSPDrv1451_InitSection4(void *p)
{
    TP_PRINTF("DSPDrv1451_InitSection4\n\r");

    cDSPDrv1451* me = (cDSPDrv1451*)p;    
    SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_POWER_ENABLE0_IC_1_ADDR, REG_POWER_ENABLE0_IC_1_BYTE, R14_POWER_ENABLE0_IC_1_Default );
    SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_POWER_ENABLE1_IC_1_ADDR, REG_POWER_ENABLE1_IC_1_BYTE, R15_POWER_ENABLE1_IC_1_Default );
    SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_ASRC_MUTE_IC_1_ADDR, REG_ASRC_MUTE_IC_1_BYTE, R16_ASRC_MUTE_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_PANIC_PARITY_MASK_IC_1_ADDR, REG_PANIC_PARITY_MASK_IC_1_BYTE, R17_PANIC_PARITY_MASK_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_ASRC_INPUT0_IC_1_ADDR, REG_ASRC_INPUT0_IC_1_BYTE, R18_ASRC_INPUT0_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_ASRC_INPUT1_IC_1_ADDR, REG_ASRC_INPUT1_IC_1_BYTE, R19_ASRC_INPUT1_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_ASRC_INPUT2_IC_1_ADDR, REG_ASRC_INPUT2_IC_1_BYTE, R20_ASRC_INPUT2_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_ASRC_OUT_RATE0_IC_1_ADDR, REG_ASRC_OUT_RATE0_IC_1_BYTE, R21_ASRC_OUT_RATE0_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_ASRC_OUT_RATE1_IC_1_ADDR, REG_ASRC_OUT_RATE1_IC_1_BYTE, R22_ASRC_OUT_RATE1_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_ASRC_OUT_RATE2_IC_1_ADDR, REG_ASRC_OUT_RATE2_IC_1_BYTE, R23_ASRC_OUT_RATE2_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE0_IC_1_ADDR, REG_SOUT_SOURCE0_IC_1_BYTE, R24_SOUT_SOURCE0_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE1_IC_1_ADDR, REG_SOUT_SOURCE1_IC_1_BYTE, R25_SOUT_SOURCE1_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE2_IC_1_ADDR, REG_SOUT_SOURCE2_IC_1_BYTE, R26_SOUT_SOURCE2_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE3_IC_1_ADDR, REG_SOUT_SOURCE3_IC_1_BYTE, R27_SOUT_SOURCE3_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE4_IC_1_ADDR, REG_SOUT_SOURCE4_IC_1_BYTE, R28_SOUT_SOURCE4_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE5_IC_1_ADDR, REG_SOUT_SOURCE5_IC_1_BYTE, R29_SOUT_SOURCE5_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE6_IC_1_ADDR, REG_SOUT_SOURCE6_IC_1_BYTE, R30_SOUT_SOURCE6_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE7_IC_1_ADDR, REG_SOUT_SOURCE7_IC_1_BYTE, R31_SOUT_SOURCE7_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE8_IC_1_ADDR, REG_SOUT_SOURCE8_IC_1_BYTE, R32_SOUT_SOURCE8_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE9_IC_1_ADDR, REG_SOUT_SOURCE9_IC_1_BYTE, R33_SOUT_SOURCE9_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE10_IC_1_ADDR, REG_SOUT_SOURCE10_IC_1_BYTE, R34_SOUT_SOURCE10_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE11_IC_1_ADDR, REG_SOUT_SOURCE11_IC_1_BYTE, R35_SOUT_SOURCE11_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE12_IC_1_ADDR, REG_SOUT_SOURCE12_IC_1_BYTE, R36_SOUT_SOURCE12_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE13_IC_1_ADDR, REG_SOUT_SOURCE13_IC_1_BYTE, R37_SOUT_SOURCE13_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE14_IC_1_ADDR, REG_SOUT_SOURCE14_IC_1_BYTE, R38_SOUT_SOURCE14_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE15_IC_1_ADDR, REG_SOUT_SOURCE15_IC_1_BYTE, R39_SOUT_SOURCE15_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE16_IC_1_ADDR, REG_SOUT_SOURCE16_IC_1_BYTE, R40_SOUT_SOURCE16_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE17_IC_1_ADDR, REG_SOUT_SOURCE17_IC_1_BYTE, R41_SOUT_SOURCE17_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE18_IC_1_ADDR, REG_SOUT_SOURCE18_IC_1_BYTE, R42_SOUT_SOURCE18_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE19_IC_1_ADDR, REG_SOUT_SOURCE19_IC_1_BYTE, R43_SOUT_SOURCE19_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE20_IC_1_ADDR, REG_SOUT_SOURCE20_IC_1_BYTE, R44_SOUT_SOURCE20_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE21_IC_1_ADDR, REG_SOUT_SOURCE21_IC_1_BYTE, R45_SOUT_SOURCE21_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE22_IC_1_ADDR, REG_SOUT_SOURCE22_IC_1_BYTE, R46_SOUT_SOURCE22_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SOUT_SOURCE23_IC_1_ADDR, REG_SOUT_SOURCE23_IC_1_BYTE, R47_SOUT_SOURCE23_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SERIAL_BYTE_1_0_IC_1_ADDR, REG_SERIAL_BYTE_1_0_IC_1_BYTE, R48_SERIAL_BYTE_1_0_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SERIAL_BYTE_2_0_IC_1_ADDR, REG_SERIAL_BYTE_2_0_IC_1_BYTE, R49_SERIAL_BYTE_2_0_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SERIAL_BYTE_3_0_IC_1_ADDR, REG_SERIAL_BYTE_3_0_IC_1_BYTE, R50_SERIAL_BYTE_3_0_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SERIAL_BYTE_5_0_IC_1_ADDR, REG_SERIAL_BYTE_5_0_IC_1_BYTE, R51_SERIAL_BYTE_5_0_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SERIAL_BYTE_6_0_IC_1_ADDR, REG_SERIAL_BYTE_6_0_IC_1_BYTE, R52_SERIAL_BYTE_6_0_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SERIAL_BYTE_7_0_IC_1_ADDR, REG_SERIAL_BYTE_7_0_IC_1_BYTE, R53_SERIAL_BYTE_7_0_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_SPDIF_RESTART_IC_1_ADDR, REG_SPDIF_RESTART_IC_1_BYTE, R54_SPDIF_RESTART_IC_1_Default );
    TP_PRINTF("DSPDrv1451_InitSection4 finish\n\r");
}

static void DSPDrv1451_InitSection5(void *p)
{
    TP_PRINTF("DSPDrv1451_InitSection5\n\r");

    //SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, PROGRAM_ADDR_IC_1, PROGRAM_SIZE_IC_1, Program_Data_IC_1 );
    cDSPDrv1451* me = (cDSPDrv1451*)p;
    uint8 buffer[PROGRAM_RAM_PAGE_SIZE+2]; 
    uint16 RegAddr;
    const uint8* bufferPtr;
    bufferPtr=Program_Data_IC_1;
    RegAddr = PROGRAM_ADDR_IC_1;
    for(RegAddr=PROGRAM_ADDR_IC_1;RegAddr<(PROGRAM_ADDR_IC_1 + (PROGRAM_SIZE_IC_1/PROGRAM_RAM_PAGE_SIZE));RegAddr++)
    {
        buffer[0]=(RegAddr>>8); 
        buffer[1]=(RegAddr&0xff);
        memcpy(&buffer[2], bufferPtr, PROGRAM_RAM_PAGE_SIZE);
        DSPDrv1451_I2cWrite(me, sizeof(buffer), (uint8*)buffer);
        bufferPtr+=PROGRAM_RAM_PAGE_SIZE;
    }
    
    TP_PRINTF("DSPDrv1451_InitSection5 finish\n\r");
}


static void DSPDrv1451_InitSection6(void *p)
{
    TP_PRINTF("DSPDrv1451_InitSection6\n\r");
    //SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, PARAM_ADDR_IC_1, PARAM_SIZE_IC_1, Param_Data_IC_1 );

    cDSPDrv1451* me = (cDSPDrv1451*)p;

    uint8 buffer[PARA_RAM_PAGE_SIZE+2]; 
    uint16 RegAddr;
    const uint8* bufferPtr;
    bufferPtr=Param_Data_IC_1;
    RegAddr = PARAM_ADDR_IC_1;
    for(RegAddr=PARAM_ADDR_IC_1;RegAddr<(PARAM_ADDR_IC_1 + (PARAM_SIZE_IC_1/PARA_RAM_PAGE_SIZE));RegAddr++)
    {
        buffer[0]=(RegAddr>>8); 
        buffer[1]=(RegAddr&0xff);
        memcpy(&buffer[2], bufferPtr, PARA_RAM_PAGE_SIZE);
        DSPDrv1451_I2cWrite(me, sizeof(buffer), (uint8*)buffer);
        bufferPtr+=PARA_RAM_PAGE_SIZE;
    }
    
    TP_PRINTF("DSPDrv1451_InitSection6 finish\n\r");
}


static void DSPDrv1451_InitSection7(void *p)
{
    TP_PRINTF("DSPDrv1451_InitSection7\n\r");
    //SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, DM1_DATA_ADDR_IC_1, DM1_DATA_SIZE_IC_1, DM1_DATA_Data_IC_1 );
    cDSPDrv1451* me = (cDSPDrv1451*)p;

    uint8 buffer[DM1_PAGE_SIZE+2]; 
    uint16 RegAddr;
    const uint8* bufferPtr;
    bufferPtr=DM1_DATA_Data_IC_1;
    RegAddr = DM1_DATA_ADDR_IC_1;
    for(RegAddr=DM1_DATA_ADDR_IC_1;RegAddr<(DM1_DATA_ADDR_IC_1 + (DM1_DATA_SIZE_IC_1/DM1_PAGE_SIZE));RegAddr++)
    {
        buffer[0]=(RegAddr>>8); 
        buffer[1]=(RegAddr&0xff);
        memcpy(&buffer[2], bufferPtr, PARA_RAM_PAGE_SIZE);
        DSPDrv1451_I2cWrite(me, sizeof(buffer), (uint8*)buffer);
        bufferPtr+=DM1_PAGE_SIZE;
    }

    TP_PRINTF("DSPDrv1451_InitSection7 finish\n\r");
}

static void DSPDrv1451_InitSection8(void *p)
{
    TP_PRINTF("DSPDrv1451_InitSection8\n\r");

    cDSPDrv1451* me = (cDSPDrv1451*)p;
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_KILL_CORE_IC_1_ADDR, REG_KILL_CORE_IC_1_BYTE, R58_KILL_CORE_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_START_ADDRESS_IC_1_ADDR, REG_START_ADDRESS_IC_1_BYTE, R59_START_ADDRESS_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_START_PULSE_IC_1_ADDR, REG_START_PULSE_IC_1_BYTE, R60_START_PULSE_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_START_CORE_IC_1_ADDR, REG_START_CORE_IC_1_BYTE, R61_START_CORE_IC_1_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_START_CORE_IC_1_ADDR, REG_START_CORE_IC_1_BYTE, R62_START_CORE_IC_1_Default );
    //SIGMA_WRITE_DELAY( DEVICE_ADDR_IC_1, R60_START_DELAY_IC_1_SIZE, R60_START_DELAY_IC_1_Default );
                               
    TP_PRINTF("DSPDrv1451_InitSection8 finish\n\r");
}

static void DSPDrv1451_InitSection9(void *p)
{
    TP_PRINTF("DSPDrv1451_InitSection9\n\r");

    cDSPDrv1451* me = (cDSPDrv1451*)p;
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_1, REG_HIBERNATE_IC_1_ADDR, REG_HIBERNATE_IC_1_BYTE, R64_HIBERNATE_IC_1_Default );

    TP_PRINTF("DSPDrv1451_InitSection9 finish\n\r");
}

static void DSPDrv1451_Xtor_Cust(cDSPDrv1451* me)
{
}


#endif /*_ADAU1451_CONFIG_*/
